using System.Numerics;
using ByteEngine.Core;
using ByteEngine.Core.Assets;
using ByteEngine.Core.Graphics;
using ByteEngine.Core.Scene;
using ByteEngine.Core.VisualLogic;
using ByteEngine.Core.Serialization;
using DuneCompany;
namespace ByteEngine.Tests;
internal sealed partial class DunePolishDiagnostic
{
 void RunMainMenu(string root){var path=Path.Combine(root,"Scenes/MainMenu.bytescene");
  VisualInstruction Instruction(string id,params (string key,EventValue value)[] values)=>new(){Id=id,Arguments=values.ToDictionary(v=>v.key,v=>v.value)};
  void Events(GameObject owner,string file,IEnumerable<(string button,string action)> buttons,bool workshop=false){var module=new EventModuleDefinition{Name=workshop?"Workshop to Main Menu":"Main Menu Navigation"};foreach(var (button,action) in buttons){var rule=new EventRuleDefinition{DisplayName=button,Conditions=[Instruction("ui.buttonClicked",("target",EventValue.String(button)))]};if(workshop)rule.Conditions.Add(Instruction("bytebard.dunecompany.building"));
    if(action is "Continue" or "New Game"){rule.Actions.Add(Instruction("bytebard.dunecompany.menu."+action.ToLowerInvariant().Replace(' ','_')));if(action=="Continue")rule.Actions.Add(Instruction("scene.load",("path",EventValue.String("Scenes/Workshop.bytescene"))));}
    else if(action=="Return"){rule.Actions.Add(Instruction("bytebard.dunecompany.save_vehicle"));rule.Actions.Add(Instruction("scene.load",("path",EventValue.String("Scenes/MainMenu.bytescene"))));}
    else if(action=="Quit")rule.Actions.Add(Instruction("game.quit"));else rule.Actions.Add(Instruction("bytebard.dunecompany.menu."+action.ToLowerInvariant().Replace(' ','_')));module.Rules.Add(rule);}
   Directory.CreateDirectory(Path.Combine(root,"Assets/Events"));new EventModuleSerializer().Save(module,Path.Combine(root,file));owner.AddComponent(new EventModuleComponent()).AddResolvedModule(new(file),module);
  }
  if(_prepare){var menu=new Scene("Dune Company - Main Menu");var camera=menu.CreateGameObject("Menu camera").AddComponent(new Camera3D{ActiveGameCamera=true});camera.Transform.WorldPosition=new(0,0,5);var canvas=menu.CreateGameObject("Main menu canvas");canvas.AddComponent(new UiCanvas());var controller=menu.CreateGameObject("Main menu events");controller.AddComponent(new DuneMainMenu3D());
   var ivory=new Vector4(.89f,.86f,.75f,1);var font=new AssetReference("Assets/GarageUI/fonts/BarlowCondensed-SemiBold.ttf");
   GameObject Widget(string name,Vector2 offset,Vector2 size,Vector4 color,GameObject? parent=null){if(parent?.GetComponent<UiWidget>() is {} panel)offset-=panel.Offset;var o=menu.CreateGameObject(name);o.SetParent(parent??canvas,false);o.AddComponent(new UiWidget{Offset=offset,Size=size,Color=color,Interactable=false});return o;}
   void Text(string name,string text,float x,float y,int size,GameObject? parent=null){if(parent?.GetComponent<UiWidget>() is {} panel){x-=panel.Offset.X;y-=panel.Offset.Y;}var o=menu.CreateGameObject(name);o.SetParent(parent??canvas,false);o.AddComponent(new UiText{Text=text,FontReference=font,FontSize=size,Color=ivory,Offset=new(x,y),OrderInLayer=10});}
   void Button(string name,string label,float x,float y,float width=230,GameObject? parent=null){var o=Widget(name,new(x,y),new(width,41),Vector4.Zero,parent);var w=o.GetComponent<UiWidget>()!;w.Kind=UiWidgetKind.Button;w.Label="";w.Interactable=true;w.HoverColor=new(.22f,.23f,.1f,.65f);w.PressedColor=new(.32f,.30f,.12f,.8f);w.DisabledColor=Vector4.Zero;w.OrderInLayer=5;Text(name+" label",label,x+25,y+5,26,parent);}
   var background=Widget("Desert menu background",Vector2.Zero,new(1280,720),Vector4.One);var image=background.GetComponent<UiWidget>()!;image.Kind=UiWidgetKind.Image;image.ImageReference=new("Assets/MainMenu/desert-menu-background.png");image.StretchHorizontal=image.StretchVertical=true;image.OrderInLayer=-10;
   Text("Dune title","DUNE",64,30,96);Text("Company title","COMPANY",64,102,96);Text("Menu tagline","B U I L D .   D R I V E .   S U R V I V E .",65,207,20);
   var options=new[]{"Continue","New Game","Settings","Credits","Quit"};for(int i=0;i<options.Length;i++)Button(options[i]+" button",string.Join(" ",options[i].ToUpperInvariant().ToCharArray()),65,269+i*56);
   Widget("Menu selection stripe",new(65,269),new(4,41),new(1,.65f,.22f,1)).GetComponent<UiWidget>()!.OrderInLayer=8;
   Widget("Save status line",new(40,657),new(42,1),new(.6f,.56f,.4f,1));Text("Save status","S A V E  0 1  /  S A L V A G E  C O N T R A C T",92,648,14);Text("Build label","E A R L Y  B U I L D",1110,663,14);
   var settings=Widget("Settings panel",new(480,215),new(540,275),new(.035f,.05f,.04f,.98f));settings.GetComponent<UiWidget>()!.OrderInLayer=20;Text("Settings title","SETTINGS",510,235,32,settings);Text("Volume value","MASTER VOLUME  100%",510,291,22,settings);Text("Quality value","GRAPHICS  FAST",510,351,22,settings);Button("Volume Down button","-",820,278,70,settings);Button("Volume Up button","+",900,278,70,settings);Button("Quality button","CHANGE",790,340,180,settings);Button("Close Settings button","BACK",510,423,150,settings);settings.Active=false;
   var credits=Widget("Credits panel",new(480,215),new(620,290),new(.035f,.05f,.04f,.98f));credits.GetComponent<UiWidget>()!.OrderInLayer=20;Text("Credits title","DUNE COMPANY",510,235,34,credits);Text("Credits text","A desert vehicle-building game\nBuilt with ByteEngine\nAsset sources and licences: ASSET-NOTICE.txt",510,294,23,credits);Button("Close Credits button","BACK",510,433,150,credits);credits.Active=false;
   Events(controller,"Assets/Events/MainMenu.byteevents",options.Select(o=>(o+" button",o)).Concat(new[]{("Volume Down button","Volume Down"),("Volume Up button","Volume Up"),("Quality button","Quality"),("Close Settings button","Close Settings"),("Close Credits button","Close Credits")}));
   // Popups must render above the primary menu, including their labels/buttons.
   foreach(var panel in new[]{settings,credits})foreach(var child in panel.Children){if(child.GetComponent<UiWidget>() is {} w)w.OrderInLayer=25;if(child.GetComponent<UiText>() is {} t)t.OrderInLayer=30;}
   _project!.AssetDatabase.Scan();_project.Scenes.Save(menu,path);
   var workshopPath=Path.Combine(root,"Scenes/Workshop.bytescene");var workshopScene=_project.Scenes.Load(workshopPath);var workshop=workshopScene.GameObjects.SelectMany(o=>o.Components).OfType<DuneWorkshop3D>().Single();var old=workshopScene.FindGameObject("Main menu button");if(old!=null)workshopScene.DestroyGameObject(old);var wc=workshopScene.GameObjects.First(o=>o.GetComponent<UiCanvas>()!=null);var returnButton=workshopScene.CreateGameObject("Main menu button");returnButton.SetParent(wc,false);returnButton.AddComponent(new UiWidget{Kind=UiWidgetKind.Button,Offset=new(1180,7),Size=new(88,32),Label="MENU",FontSize=17,Color=new(.12f,.17f,.11f,1),HoverColor=new(.25f,.3f,.15f,1),OrderInLayer=10});
   var existing=workshop.GameObject.Components.OfType<EventModuleComponent>().FirstOrDefault(c=>c.Modules.Any(r=>r.CachedProjectPath=="Assets/Events/WorkshopNavigation.byteevents"));if(existing==null)Events(workshop.GameObject,"Assets/Events/WorkshopNavigation.byteevents",[("Main menu button","Return")],true);
   _project.AssetDatabase.Scan();_project.Scenes.Save(workshopScene,workshopPath);_project.Project.StartupScene="Scenes/MainMenu.bytescene";new ProjectSerializer().Save(_project.Project,_file);
  }
  Scenes.SceneFactory=relative=>{var watch=System.Diagnostics.Stopwatch.StartNew();var next=_project!.Scenes.Load(ByteEngine.Core.Runtime.GamePackageExporter.ResolveInside(root,relative));Console.WriteLine($"DESERIALIZE {relative}: {watch.Elapsed.TotalMilliseconds:0} ms");return next;};bool quit=false;Scenes.QuitHandler=()=>quit=true;Scenes.LoadScene(_project!.Scenes.Load(path));
  void Step(float x,float y,bool click=false){var raw=new ByteEngine.Core.InputSystem.RawInputSnapshot();if(click)raw.MouseButtonsDown.Add(MouseButton.Left);Input.UpdatePortable(raw,false);Input.SetGameViewPointer(new(x/1280,y/720),new(1280,720),true);Time.Update(1f/60);Scenes.UpdateInternal();}
  Step(100,280);Step(100,457);if(Scenes.ActiveScene!.FindGameObject("Menu selection stripe")!.GetComponent<UiWidget>()!.Offset.Y!=269+3*56)throw new InvalidOperationException("Menu hover loses to previous focus");Step(100,280);Capture(Scenes.ActiveScene!,Path.Combine(root,"Preview/main-menu-native.png"),false);
  Step(130,401,true);Step(130,289);if(Scenes.ActiveScene!.FindGameObject("Continue button")!.GetComponent<UiWidget>()!.WasClicked)throw new InvalidOperationException("Modal dialog allows clicking menu behind it");if(Scenes.ActiveScene!.FindGameObject("Settings panel")?.Active!=true)throw new InvalidOperationException("Settings events do not open native panel");Step(950,299);Step(950,299,true);Step(560,440);Step(560,440,true);if(Scenes.ActiveScene.FindGameObject("Settings panel")!.Active)throw new InvalidOperationException("Settings Back event failed");
  Step(130,457);Step(130,457,true);if(!Scenes.ActiveScene.FindGameObject("Credits panel")!.Active)throw new InvalidOperationException("Credits event failed");Step(560,450);Step(560,450,true);
  string? savedVehicle=File.Exists(Path.Combine(root,"Saves/vehicle.json"))?File.ReadAllText(Path.Combine(root,"Saves/vehicle.json")):null;Step(130,345);Scenes.ShowLoadingScreen=true;Step(130,345,true);Step(130,345);if(Scenes.ActiveScene!.FindGameObject("New Game confirmation")?.Active!=true)throw new InvalidOperationException("New Game confirmation missing");Capture(Scenes.ActiveScene!,Path.Combine(root,"Preview/new-game-confirmation.png"),false);string paymentFile=Path.Combine(root,"Saves/recovery-payment.json");var progressBefore=File.Exists(paymentFile)?File.ReadAllText(paymentFile):null;Step(460,440);Step(460,440,true);Step(130,345);if(Scenes.ActiveScene!.FindGameObject("New Game confirmation")!.Active||Scenes.ActiveScene.Name!="Dune Company - Main Menu"||(File.Exists(paymentFile)?File.ReadAllText(paymentFile):null)!=progressBefore)throw new Exception("Cancel changed the campaign");Step(130,345,true);Step(820,440);Step(820,440,true);if(!Scenes.ActiveScene!.LoadingScreenVisible)throw new InvalidOperationException("Loading overlay not queued");Capture(Scenes.ActiveScene!,Path.Combine(root,"Preview/scene-loading.png"),false);Step(130,345);Scenes.ShowLoadingScreen=false;if(Scenes.ActiveScene!.GameObjects.SelectMany(o=>o.Components).OfType<DuneWorkshop3D>().Single().Blocks.Count!=1)throw new InvalidOperationException("New Game did not start a fresh build");var fresh=Scenes.ActiveScene.GameObjects.SelectMany(o=>o.Components).OfType<DuneWorkshop3D>().Single();if(fresh.RecoveryPayment!=0||File.Exists(Path.Combine(root,"Saves/tow-progress-v1.json"))||File.Exists(Path.Combine(root,"Saves/winch-progress-v1.json")))throw new Exception("Confirmed new game retained campaign progress");fresh.Command("Open contracts");Step(640,350);if(!Scenes.ActiveScene.FindGameObject("Contract row tow")!.ActiveInHierarchy||!Scenes.ActiveScene.FindGameObject("Contract row winch")!.ActiveInHierarchy)throw new Exception("New Game did not restore both available contracts");Capture(Scenes.ActiveScene,Path.Combine(root,"Preview/new-game-fresh-contracts.png"),false);fresh.Command("Close garage overlay");Step(1220,23);Step(1220,23,true);if(Scenes.ActiveScene!.Name!="Dune Company - Main Menu")throw new InvalidOperationException("Workshop menu event did not load the menu scene");
  if(savedVehicle!=null)File.WriteAllText(Path.Combine(root,"Saves/vehicle.json"),savedVehicle);Step(130,289);Step(130,289,true);if(!Scenes.ActiveScene!.GameObjects.SelectMany(o=>o.Components).OfType<DuneWorkshop3D>().Any())throw new InvalidOperationException("Continue scene transition failed");Step(1220,23);Step(1220,23,true);Step(130,513);Step(130,513,true);if(!quit)throw new InvalidOperationException("Quit event failed");
  Console.WriteLine("PASS Native menu save/reload; settings; credits; New Game -> Workshop -> Menu -> Continue; Quit event");Scenes.UnloadScene();_project.Dispose();Close();
 }
}
