using System.Numerics;
using System.Text.Json;
using ByteEngine.Core;
using ByteEngine.Core.Assets;
using ByteEngine.Core.Graphics;
using ByteEngine.Core.Graphics.ThreeD;
using ByteEngine.Core.Scene;
namespace ByteEngine.Tests;
internal sealed partial class DunePolishDiagnostic
{
 void RunGarage(string root)
 {
  if(Environment.GetEnvironmentVariable("DUNE_WINCH_FLOW")=="1"){RunWinchFlow(root);return;}
  using var contractRuntime=Environment.GetEnvironmentVariable("DUNE_CONTRACT_RUNTIME")=="1"?new ByteEngine.Core.Runtime.GameProjectRuntime(_file,Console.WriteLine):null;
  string path=Path.Combine(root,"Scenes/Workshop.bytescene");var scene=contractRuntime?.LoadStartupScene()??_project!.Scenes.Load(path);
  if(_prepare)AuthorGarage(scene,root,path);
  if(Environment.GetEnvironmentVariable("DUNE_CONTRACT_NAV")=="1")scene=_project.Scenes.CloneForRuntime(scene);Scenes.LoadScene(scene);Tick(scene,new(.5f),false);foreach(var c in scene.GameObjects.SelectMany(o=>o.Components).Where(c=>c.GetType().Name.Contains("Workshop")))Console.WriteLine("WORKSHOP TYPE "+c.GetType().AssemblyQualifiedName+" / expected "+typeof(DuneCompany.DuneWorkshop3D).Assembly.Location);var workshop=scene.GameObjects.SelectMany(o=>o.Components).OfType<DuneCompany.DuneWorkshop3D>().Single();if(Environment.GetEnvironmentVariable("DUNE_WEB_PREVIEWS")=="1"){workshop.BakeStarterWebPreviews();Console.WriteLine("PASS Starter web previews baked");Close();return;}if(Environment.GetEnvironmentVariable("DUNE_CONTRACT_NAV")=="1"){
RunUnifiedContracts(root,scene,workshop);Close();return;}
workshop.Command("Load vehicle");Tick(scene,new(.5f),false);
  Capture(scene,Path.Combine(root,"Preview/grit-garage.png"),false);
  foreach(var size in new[]{new Vector2(960,540),new Vector2(1600,1000),new Vector2(1920,800)}){Input.SetGameViewPointer(new(.5f),size,true);Time.Update(1f/60);scene.UpdateInternal();using var fb=new ByteEngine.Editor.SceneFramebuffer();fb.RenderGame(Renderer,Renderer3D,scene,ByteEngine.Editor.EditorMode.Play,(int)size.X,(int)size.Y,(int)size.X,(int)size.Y);OpenTK.Graphics.OpenGL4.GL.Finish();var pixels=new byte[(int)(size.X*size.Y)*4];OpenTK.Graphics.OpenGL4.GL.BindTexture(OpenTK.Graphics.OpenGL4.TextureTarget.Texture2D,(int)fb.TextureId);OpenTK.Graphics.OpenGL4.GL.GetTexImage(OpenTK.Graphics.OpenGL4.TextureTarget.Texture2D,0,OpenTK.Graphics.OpenGL4.PixelFormat.Rgba,OpenTK.Graphics.OpenGL4.PixelType.UnsignedByte,pixels);OpenTK.Graphics.OpenGL4.GL.BindTexture(OpenTK.Graphics.OpenGL4.TextureTarget.Texture2D,0);Png(Path.Combine(root,$"Preview/grit-{size.X}x{size.Y}.png"),pixels,(int)size.X,(int)size.Y);}
  Tick(scene,new(.5f),false);
  if(scene.GameObjects.Any(o=>o.GetComponent<UiText>()?.Text=="DUNE COMPANY"))throw new Exception("Game name remains in garage header");
  // Every click uses the authored widget rectangle, not obsolete toolbar coordinates.
  void Click(string name){var button=scene.FindGameObject(name)!.GetComponent<UiWidget>()!;var r=UiLayout.Resolve(button.GameObject,button.Anchor,button.Offset,button.Size,new(1280,720));var p=(r.Position+r.Size*.5f)/new Vector2(1280,720);Tick(scene,p,false);Tick(scene,p,true);Tick(scene,p,false);}
  Click("Contracts tab");Click("Contract expand");if(!scene.FindGameObject("Contracts overlay")!.ActiveInHierarchy)throw new Exception("Contracts navigation failed");Capture(scene,Path.Combine(root,"Preview/grit-contracts.png"),false);Click("Close garage overlay");
  Click("Blueprints tab");if(!scene.FindGameObject("Blueprints overlay")!.ActiveInHierarchy)throw new Exception("Blueprints navigation failed");if(Environment.GetEnvironmentVariable("DUNE_MENUS_SMOKE")!="1")RunGarageMenuChecks(scene,workshop,root,Click);Click("Close garage overlay");
  Click("Search parts");foreach(var key in new[]{Key.W,Key.H,Key.E,Key.E,Key.L}){Tick(scene,new(.5f),false,key);Tick(scene,new(.5f),false);}Tick(scene,new(.5f),false,Key.Enter);if(scene.FindGameObject("Search parts")!.GetComponent<UiWidget>()!.Label!="wheel")throw new Exception("Search typing failed: "+scene.FindGameObject("Search parts")!.GetComponent<UiWidget>()!.Label);Click("Clear search");
  var spring=workshop.Blocks.FirstOrDefault(b=>b.Type is 16 or 17 or 32);if(spring!=null){typeof(DuneCompany.DuneWorkshop3D).GetField("_selected",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance)!.SetValue(workshop,spring.Id);workshop.Command("Tune selected");Tick(scene,new(.5f),false);Capture(scene,Path.Combine(root,"Preview/grit-tuning.png"),false);Click("Tuning numeric value 0");foreach(var key in new[]{Key.D0,Key.Period,Key.D3,Key.D3}){Tick(scene,new(.5f),false,key);Tick(scene,new(.5f),false);}Tick(scene,new(.5f),false,Key.Enter);Tick(scene,new(.5f),false);if(Math.Abs(spring.Travel-.33f)>.001f)throw new Exception("Numeric tuning commit failed");var slider=scene.FindGameObject("Button 944,158")!.GetComponent<UiWidget>()!;var sliderRect=UiLayout.Resolve(slider.GameObject,slider.Anchor,slider.Offset,slider.Size,new(1280,720));var sliderPointer=(sliderRect.Position+sliderRect.Size*new Vector2(.75f,.5f))/new Vector2(1280,720);Tick(scene,sliderPointer,false);Tick(scene,sliderPointer,true);Tick(scene,sliderPointer,false);if(Math.Abs(spring.Travel-.38f)>.005f)throw new Exception("Slider drag failed");Click("Button 1223,88");}
  if(Environment.GetEnvironmentVariable("DUNE_RECOVERY_FLOW")=="1"){
   Click("Tune blocks");var wheel=workshop.Blocks.First(b=>b.Type==13);var visual=scene.FindGameObject("Block "+wheel.Id+" - "+workshop.Catalog[wheel.Type].Label)!;var point=Vector3.Transform(new Vector3(0,0,-.18f),visual.Transform.WorldMatrix);var pointer=Pointer(scene.ActiveCamera!,point);Tick(scene,pointer,false);Tick(scene,pointer,true);Tick(scene,pointer,false);if(!scene.FindGameObject("Block tuning panel")!.ActiveInHierarchy||workshop.HighlightedBlock<0)throw new Exception("Toolbar tuning did not select a placed component");Click("Button 1223,88");Click("Place blocks");
   var elevation=typeof(DuneCompany.DuneWorkshop3D).GetField("_elevation",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance)!;elevation.SetValue(workshop,-.65f);Tick(scene,new(.5f),false);if(scene.GameObjects.SelectMany(o=>o.Components).OfType<ByteEngine.Core.Gameplay.InteractiveSand3D>().Any(s=>s.Enabled))throw new Exception("Ground remains visible under the build camera");Capture(scene,Path.Combine(root,"Preview/recovery-underside.png"),false);elevation.SetValue(workshop,.5f);Tick(scene,new(.5f),false);if(scene.GameObjects.SelectMany(o=>o.Components).OfType<ByteEngine.Core.Gameplay.InteractiveSand3D>().Any(s=>!s.Enabled))throw new Exception("Ground visibility was not restored");Console.WriteLine("PASS Toolbar tuning selects actual component; underside orbit hides and restores ground");
  }
  Click("Run / build");if(workshop.Building||scene.FindGameObject("Garage environment")!.ActiveInHierarchy||scene.FindGameObject("Garage build UI")!.ActiveInHierarchy)throw new Exception("Test drive did not hide garage/UI");for(int i=0;i<100;i++)Tick(scene,new(.5f),false,Key.W);Capture(scene,Path.Combine(root,"Preview/grit-drive.png"),false);Click("Return workshop");if(!workshop.Building||!scene.FindGameObject("Garage environment")!.ActiveInHierarchy)throw new Exception("Return did not restore garage");
  Click("Contracts tab");if(!scene.FindGameObject("Contract details")!.ActiveInHierarchy)Click("Contract expand");Click("Deploy contract");if(!workshop.Blocks.Any(b=>b.Type==20)){Console.WriteLine("PASS Missing hinge blocks contract deployment");workshop.AddBlock(20,0,new(0,0,2),Quaternion.Identity);Click("Deploy contract");}if(workshop.Building||!workshop.MissionActive)throw new Exception("Contract deployment failed");Tick(scene,new(.5f),false,Key.B);if(workshop.Building)throw new Exception("Active contract allowed building");Click("Quit contract");if(!workshop.Building||workshop.MissionActive)throw new Exception("Quit contract did not restore garage");
  if(Environment.GetEnvironmentVariable("DUNE_RECOVERY_FLOW")=="1"){RunRecoveryFlow(scene,workshop,root);RunRecoveryFlow(scene,workshop,root,true);Click("Contracts tab");Click("Contracts completed");Click("Contract expand");Capture(scene,Path.Combine(root,"Preview/menus-completed-deliveries.png"),false);Click("Close garage overlay");}
  Scenes.UnloadScene();scene=_project.Scenes.Load(path);Scenes.LoadScene(scene);Tick(scene,new(.5f),false);if(scene.FindGameObject("Garage environment")==null||scene.FindGameObject("Search parts")==null)throw new Exception("Garage failed scene reload");Scenes.UnloadScene();_project.Dispose();Console.WriteLine("PASS Authored garage import/save/reload, search, contracts, blueprints, tuning, native mouse test drive and return; garage rendering absent during driving");Close();
 }
 void AuthorGarage(Scene scene,string root,string path)
 {
  foreach(var workshop in scene.GameObjects.SelectMany(o=>o.Components).OfType<DuneCompany.DuneWorkshop3D>())workshop.MaximumSpeed=Math.Max(50,workshop.MaximumSpeed);
  // Remove old UI descendants and previous garage only. Vehicle, sand and mission objects survive.
  foreach(var canvas in scene.GameObjects.Where(o=>o.GetComponent<UiCanvas>()!=null).ToArray())scene.DestroyGameObject(canvas);
  // Menu-only upgrade preserves the user's garage, lighting, terrain and authored contract.
  if(scene.FindGameObject("Garage environment")==null){var garage=scene.CreateGameObject("Garage environment");garage.Transform.LocalRotation=Quaternion.CreateFromAxisAngle(Vector3.UnitY,MathF.PI);DuneCompany.DuneWorkshop3D.Model(scene,_project!.Assets,"Assets/GritGarage/grit-garage.glb",garage,"Scrapyard garage kit");}
  var canvasRoot=scene.CreateGameObject("Garage UX v2 canvas");canvasRoot.AddComponent(new UiCanvas{ReferenceResolution=new(1280,720)});
  GameObject Group(string name,GameObject? parent=null){var o=scene.CreateGameObject(name);o.SetParent(parent??canvasRoot,false);return o;}
  var build=Group("Garage build UI");var drive=Group("Garage driving UI");drive.Active=false;
  Vector4 ink=new(.055f,.058f,.057f,.97f),card=new(.105f,.108f,.105f,1),ivory=new(.91f,.88f,.82f,1),muted=new(.64f,.63f,.59f,1),amber=new(.94f,.66f,.29f,1),edge=new(.23f,.23f,.21f,1);
  AssetReference regular=new("Assets/GarageUI/fonts/Barlow-Regular.ttf"),heading=new("Assets/GarageUI/fonts/BarlowCondensed-SemiBold.ttf");
  GameObject Widget(string name,Vector2 pos,Vector2 size,Vector4 color,GameObject parent,int order=1){if(parent.GetComponent<UiWidget>() is {} pw)pos-=UiLayout.Resolve(parent,pw.Anchor,pw.Offset,pw.Size,new(1280,720)).Position;var o=Group(name,parent);o.AddComponent(new UiWidget{Offset=pos,Size=size,Color=color,Interactable=false,Label="",OrderInLayer=order});return o;}
  void Text(string name,string label,float x,float y,int size,GameObject parent,Vector4? color=null,float wrap=0,int order=10){Vector2 pos=new(x,y);if(parent.GetComponent<UiWidget>() is {} pw)pos-=UiLayout.Resolve(parent,pw.Anchor,pw.Offset,pw.Size,new(1280,720)).Position;var o=Group(name,parent);o.AddComponent(new UiText{Text=label,Offset=pos,FontSize=size,FontReference=size>=20?heading:regular,Color=color??ivory,WrapWidth=wrap,OrderInLayer=order});}
  GameObject Button(string name,string label,float x,float y,float w,float h,GameObject parent,bool primary=false,int size=16,int order=5){var o=Widget(name,new(x,y),new(w,h),primary?amber:card,parent,order);var b=o.GetComponent<UiWidget>()!;b.Kind=UiWidgetKind.Button;b.Label=label;b.FontSize=size;b.FontReference=regular;b.Interactable=true;b.HoverColor=primary?new(1,.75f,.39f,1):new(.22f,.20f,.16f,1);b.PressedColor=new(.43f,.32f,.18f,1);b.DisabledColor=new(.13f,.13f,.12f,1);if(primary){b.Label="";var caption=Group(name+" caption",o);caption.AddComponent(new UiText{Text=label,Anchor=UiAnchor.Center,Offset=Vector2.Zero,FontSize=size,FontReference=regular,Color=new(.10f,.08f,.055f,1),OrderInLayer=order+1});}return o;}
  void Image(string name,string file,float x,float y,float w,float h,GameObject parent){var o=Widget(name,new(x,y),new(w,h),Vector4.One,parent,8);o.GetComponent<UiWidget>()!.OrderInLayer=Math.Max(8,(parent.GetComponent<UiWidget>()?.OrderInLayer??0)+4);o.GetComponent<UiWidget>()!.Kind=UiWidgetKind.Image;o.GetComponent<UiWidget>()!.ImageReference=string.IsNullOrEmpty(file)?AssetReference.Empty:new(file);}
  void Rule(string name,float x,float y,float w,GameObject parent){Widget(name,new(x,y),new(w,1),edge,parent);}
  Text("Garage UX v2","",0,0,12,build);
  var top=Widget("Garage top bar",Vector2.Zero,new(1280,48),ink,build);top.GetComponent<UiWidget>()!.StretchHorizontal=true;
  Button("Garage tab","GARAGE",18,5,95,38,build);Button("Contracts tab","CONTRACTS",125,5,115,38,build);Button("Blueprints tab","BLUEPRINTS",252,5,120,38,build);Widget("Garage active tab",new(18,45),new(95,3),amber,build);
  Text("Garage vehicle name","Vehicle 01",1020,15,16,build);Text("Garage save status","Saved",1125,15,15,build,muted);Button("Save machine","SAVE CHANGES",384,8,126,32,build,false,13);Button("Main menu button","MENU",1200,8,65,32,build,false,13);var menuButton=scene.FindGameObject("Main menu button")!.GetComponent<UiWidget>()!;menuButton.Anchor=UiAnchor.TopRight;menuButton.Offset=new(-15,8);var vehicleName=scene.FindGameObject("Garage vehicle name")!.GetComponent<UiText>()!;vehicleName.Anchor=UiAnchor.TopRight;vehicleName.Offset=new(-180,15);var saveStatus=scene.FindGameObject("Garage save status")!.GetComponent<UiText>()!;saveStatus.Anchor=UiAnchor.TopRight;saveStatus.Offset=new(-105,15);
  var left=Widget("Parts catalogue",new(0,48),new(248,616),ink,build);Text("Parts title","PARTS",20,69,27,left);
  Button("Search parts","Search parts...",14,109,188,36,left,false,15);Button("Clear search","X",208,109,26,36,left,false,14);
  string[] labels=["Structure","Wheels","Weapons","Mechanical","Body"];
  for(int i=0;i<5;i++){float x=i<3?14+i*74:14+(i-3)*110;float y=i<3?155:185;Button($"Button {8+i*42},639",labels[i],x,y,i<3?70:106,26,left,false,13);}
  for(int i=0;i<6;i++){float x=14+i%2*116,y=225+i/2*135;Widget("Part selection "+i,new(x,y),new(104,125),edge,left,2);Button($"Button {239+i*106},633","",x+1,y+1,102,123,left);Image("Part "+i,"",x+6,y+6,92,84,left);Text("Part name "+i,"Part",x+7,y+92,13,left,ivory,91);}
  Button("Button 880,634","<",14,631,30,25,left);Text("Catalogue page","1 / 1",97,636,13,left,muted);Button("Button 880,674",">",204,631,30,25,left);Text("Search empty","",20,265,17,left,muted,210);
  var right=Widget("Garage inspector",new(1000,48),new(280,672),ink,build);right.GetComponent<UiWidget>()!.Anchor=UiAnchor.TopRight;right.GetComponent<UiWidget>()!.Offset=new(0,48);
  Text("Selected block","SELECT A PART",1020,72,21,right,ivory,180);Image("Inspector part preview","",1205,63,58,58,right);Text("Block function","Choose a component to see its function.",1020,127,12,right,muted,236);Rule("Inspector divider",1020,190,240,right);
  Button("Tune selection","TUNE PLACED PART",1020,198,240,28,right,false,14);
  var tuning=Widget("Block tuning panel",new(1000,198),new(280,241),ink,right,3);tuning.Active=false;Text("Tuning heading","",0,0,8,tuning);scene.FindGameObject("Tuning heading")!.Active=false;
  for(int i=0;i<6;i++){float y=210+i*31;Text("Tuning value "+i,"",1020,y,13,tuning,ivory,225);var track=Button($"Button 944,{158+i*57}","",1020,y+12,156,24,tuning);track.GetComponent<UiWidget>()!.Color=Vector4.Zero;track.GetComponent<UiWidget>()!.HoverColor=Vector4.Zero;track.GetComponent<UiWidget>()!.PressedColor=Vector4.Zero;var bar=Widget("Tuning slider fill "+i,new(1020,y+18),new(156,8),new(.21f,.21f,.20f,1),tuning,6);bar.GetComponent<UiWidget>()!.Kind=UiWidgetKind.ProgressBar;bar.GetComponent<UiWidget>()!.FillColor=amber;Widget("Tuning slider knob "+i,new(1020,y+15),new(8,14),ivory,tuning,7);Button("Tuning numeric value "+i,"0",1185,y+4,72,27,tuning,false,14);}
  Button("Button 944,494","Reset",1020,403,66,28,tuning,false,13);Button("Button 1098,494","Apply to same",1090,403,115,28,tuning,false,13);Button("Button 1223,88","X",1220,403,37,28,tuning,false,13);
  Rule("Summary divider",1020,437,240,right);Text("Summary title","VEHICLE SUMMARY",1020,451,18,right);
  Text("Mass caption","Mass",1020,486,15,right,muted);Text("Garage mass","0 kg",1210,486,15,right);Text("Wheels caption","Wheels",1020,513,15,right,muted);Text("Garage wheels","0",1233,513,15,right);Text("Engine caption","Engines",1020,540,15,right,muted);Text("Garage engines","0",1233,540,15,right);
  Rule("Readiness divider",1020,570,240,right);Text("Garage readiness","BUILD REQUIREMENTS",1020,584,18,right,new(.7f,.8f,.59f,1));Image("Requirement seat","",1020,605,28,28,right);Image("Requirement engine","",1100,605,28,28,right);Image("Requirement wheel","",1180,605,28,28,right);Text("Seat readiness","Seat",1051,611,10,right,ivory,46);Text("Engine readiness","Engine",1131,611,10,right,ivory,46);Text("Wheel readiness","Wheel",1211,611,10,right,ivory,46);Text("Garage drive hint","",1020,568,11,right,muted,236);
  Button("Run / build","TEST DRIVE",1015,638,119,48,right,false,15);Button("Contracts action","CONTRACTS",1140,638,125,48,right,true,15);
  var bottom=Widget("Garage command strip",new(0,664),new(1000,56),ink,build);Button("Rotate mount","Rotate R",260,674,86,34,bottom,false,14);Button("Move branch","Move",352,674,64,34,bottom,false,14);Button("Copy part","Duplicate",422,674,90,34,bottom,false,14);Button("Erase blocks","Delete",518,674,70,34,bottom,false,14);Button("Undo","Undo",594,674,60,34,bottom,false,14);Button("Redo","Redo",660,674,60,34,bottom,false,14);Button("Place blocks","Build",726,674,60,34,bottom,false,14);Button("Change mount face","Face T",792,674,70,34,bottom,false,14);Button("Tune blocks","Tune",868,674,75,34,bottom,true,14);
  Widget("Garage instruction background",new(248,599),new(752,65),new(.04f,.045f,.04f,.90f),build);
  Text("Placement instruction","Choose a part, then click a mounting surface.",260,630,14,build,ivory,720);Text("Build controls","RMB / MMB orbit    Scroll zoom    R / F / G rotate",260,607,13,build,muted,720);
  var tooltip=Widget("Context tooltip",new(270,488),new(355,100),ink,build,20);Text("Tooltip heading","",284,500,18,tooltip,amber,325,22);Text("Tooltip explanation","",284,529,14,tooltip,ivory,325,22);tooltip.Active=false;
  Widget("Overlay backdrop",new(248,48),new(752,616),new(.025f,.028f,.027f,.97f),build,30).Active=false;
  var contracts=Widget("Contracts overlay",new(280,90),new(688,510),ink,build,31);contracts.Active=false;Text("Contracts title","CONTRACTS",307,117,32,contracts,ivory,0,35);Text("Contracts subtitle","Available jobs",307,158,14,contracts,muted,600,35);Button("Contracts available","AVAILABLE",307,182,132,30,contracts,false,14,35);Button("Contracts completed","COMPLETED",445,182,142,30,contracts,false,14,35);Button("Contract expand","Stranded in the sand    +",307,222,608,46,contracts,false,18,35);Text("Contracts empty","",307,290,18,contracts,muted,600,35);
  var details=Widget("Contract details",new(307,279),new(608,299),card,contracts,34);details.Active=false;Text("Contract name","STRANDED IN THE SAND",323,292,24,details,amber,470,35);Text("Contract reward","$250",832,292,24,details,amber,0,35);Text("Contract history","LOCAL RECOVERY / ONE BUGGY",323,324,13,details,muted,550,35);Text("Contract brief","Tow the stranded buggy out of the hollow and back to the garage.\nAlign the hitches, press H to connect. R resets both vehicles.",323,352,16,details,ivory,558,35);Text("Contract parts heading","REQUIRED PARTS",323,410,13,details,muted,0,35);
  int[] required=[25,23,13,20];string[] requiredLabels=["Seat","Engine","Wheels","Trailer hinge"];var catalogue=JsonSerializer.Deserialize<List<DuneCompany.DunePart>>(File.ReadAllText(Path.Combine(root,"Assets/DuneParts/catalog.json")),DuneCompany.BuildStore.Json)!;for(int i=0;i<4;i++){float x=323+i*110;Image("Contract required "+i,catalogue.First(p=>p.Id==required[i]).Preview,x,429,50,44,details);Text("Contract required label "+i,requiredLabels[i],x,476,12,details,ivory,100,35);}Text("Contract requirements","Fit a trailer hinge",323,499,12,details,amber,554,35);Button("Deploy contract","ACCEPT & DEPLOY",323,526,220,38,details,true,16,35);
  var blueprints=Widget("Blueprints overlay",new(280,90),new(688,510),ink,build,31);blueprints.Active=false;Text("Blueprint title","BLUEPRINTS",307,117,32,blueprints,ivory,0,35);Text("Blueprint description","Choose a saved vehicle",307,167,13,blueprints,muted,605,35);for(int i=0;i<4;i++){float x=307+i%2*314,y=199+i/2*143;Button("Blueprint row "+i,"",x,y,300,132,blueprints,false,16,35);Image("Blueprint thumbnail "+i,"",x+9,y+5,282,86,blueprints);scene.FindGameObject("Blueprint thumbnail "+i)!.GetComponent<UiWidget>()!.OrderInLayer=36;Text("Blueprint label "+i,"",x+10,y+89,15,blueprints,ivory,0,38);Text("Blueprint stats "+i,"",x+10,y+112,11,blueprints,muted,210,38);Button("Blueprint delete "+i,"DELETE",x+225,y+97,68,25,blueprints,false,9,40);}
  Button("Blueprint update","SAVE CHANGES",307,492,166,42,blueprints,true,14,35);Button("Blueprint new","SAVE NEW",482,492,135,42,blueprints,false,14,35);Button("Blueprint previous","<",750,497,35,32,blueprints,false,16,35);Text("Blueprint page","1 / 1",797,504,14,blueprints,muted,0,35);Button("Blueprint next",">",880,497,35,32,blueprints,false,16,35);Text("Blueprint notice","Click a vehicle to load it. Current changes can be saved from the garage.",307,552,13,blueprints,muted,600,35);
  var naming=Widget("Blueprint naming",new(347,234),new(552,240),ink,blueprints,60);naming.Active=false;Text("Blueprint naming title","NAME YOUR VEHICLE",371,254,27,naming,ivory,0,65);Text("Blueprint name hint","Up to 32 characters / Enter to save / Escape to cancel",371,295,13,naming,muted,500,65);Button("Blueprint name field","",371,329,504,43,naming,false,18,65);Button("Blueprint name confirm","SAVE BLUEPRINT",371,401,220,42,naming,true,15,65);Button("Blueprint name cancel","CANCEL",607,401,140,42,naming,false,15,65);
  Button("Close garage overlay","BACK",856,106,90,36,build,false,15,40).Active=false;
  Widget("Drive objective background",new(14,14),new(720,46),new(.035f,.04f,.035f,.88f),drive);
  Text("Battle objective","TEST DRIVE",22,22,19,drive,ivory,850);Widget("Recovery interaction background",new(14,65),new(850,34),new(.035f,.04f,.035f,.9f),drive);Text("Recovery interaction","",22,70,17,drive,ivory,1000);Text("Recovery marker label","",640,160,18,drive,amber);Text("Machine status","0 km/h",22,653,24,drive);Button("Return workshop","RETURN TO GARAGE",1046,655,214,44,drive,false,16);Button("Quit contract","QUIT CONTRACT",1046,655,214,44,drive,false,16);Button("Recover machine","RECOVER R",22,685,120,28,drive,false,13);
  // Keep legacy event-facing labels available, but omit them from the visual layout.
  foreach(string name in new[]{"Machine count","Simulation mode","Workshop title"}){Text(name,"",0,0,10,build);scene.FindGameObject(name)!.Active=false;}
  _project!.AssetDatabase.Scan();_project.Scenes.Save(scene,path);Console.WriteLine("PASS Scene-authored garage saved with real imported meshes and independently editable UI controls");
 }
}
