using ByteEngine.Editor;
using System.Numerics;
using System.Text.Json;
using System.Globalization;
using ByteEngine.Core;
using ByteEngine.Core.Audio;
using ByteEngine.Core.Graphics;
using ByteEngine.Core.Graphics.ThreeD;
using ByteEngine.Core.Scene;
using ByteEngine.Core.Vfx;
using DuneCompany;
using DesertTerrain;
namespace ByteEngine.Tests;
internal sealed partial class DunePolishDiagnostic
{
 void RunDesertSlice(Scene scene,DesertTerrain3D terrain,string root,string path)
 {
  using var layout=JsonDocument.Parse(File.ReadAllText(Path.Combine(root,"Assets/DesertSlice/layout.json")));var points=layout.RootElement.GetProperty("road").EnumerateArray().Select(p=>new Vector2(p[0].GetSingle(),p[1].GetSingle())).ToArray();
  if(_world){using var world=JsonDocument.Parse(File.ReadAllText(Path.Combine(root,"Assets/MissionWorld/world-layout.json")));points=world.RootElement.GetProperty("routes")[0].GetProperty("points").EnumerateArray().Select(p=>new Vector2(p[0].GetSingle(),p[1].GetSingle())).ToArray();}
  if(_prepare&&!_world){
   terrain.HeightmapPath="Assets/DesertSlice/garage-salvage-heightmap.png";terrain.PackedSurfaceMaskPath="Assets/DesertSlice/packed-road-mask.png";terrain.Cells=512;terrain.Spacing=2;terrain.HeightmapHeight=48;terrain.FlipHeightmapX=terrain.FlipHeightmapZ=false;terrain.BaseHeight=0;terrain.SandAlbedoPath="Assets/DesertSlice/dune-sand-diff.jpg";terrain.SandNormalPath="Assets/DesertSlice/dune-sand-normal.jpg";terrain.SandRoughnessPath="Assets/DesertSlice/dune-sand-rough.jpg";terrain.SandColor=new(1,.90f,.74f,1);terrain.TextureWorldSize=30;terrain.NormalStrength=.12f;terrain.MaximumRutDepth=.10f;terrain.LooseGrip=.70f;terrain.PackedGrip=1.08f;terrain.LooseResistance=.12f;terrain.ReceiveShadowsDistance=80;terrain.Regenerate();terrain.ResetSand();
   var sky=scene.GameObjects.SelectMany(o=>o.Components).OfType<SkyEnvironment>().Single();sky.EnvironmentMapReference=new("Assets/DesertSlice/desert-pure-sky.hdr");sky.Quality=GraphicsQuality.Fast;sky.SkyMode=SkyMode3D.EnvironmentMap;sky.SkyIntensity=.45f;sky.EnvironmentIntensity=.65f;sky.EnvironmentRotationDegrees=65;sky.Exposure=.95f;sky.Warmth=.04f;sky.Contrast=1.05f;sky.Saturation=.94f;sky.AmbientIntensity=.22f;sky.AmbientOcclusion=0;sky.OcclusionRadius=.4f;sky.Bloom=0;sky.FogDensity=.00065f;sky.FogMaxOpacity=.5f;sky.FogColor=new(.71f,.72f,.70f);
   var sun=scene.GameObjects.SelectMany(o=>o.Components).OfType<DirectionalLight>().First();sun.Transform.EulerAngles=new(37,-52,0);sun.Color=new(1,.94f,.83f);sun.Intensity=1.9f;sun.ShadowDistance=70;sun.ShadowResolution=2048;sun.ShadowSoftness=1.5f;
   foreach(var o in scene.GameObjects.Where(o=>o.Name=="Desert backdrop"||o.Name.StartsWith("Sandstone landmark ")||o.Name.StartsWith("Slice - ")).ToArray())scene.DestroyGameObject(o);
   GameObject Prop(string label,string file,Vector3 position,float scale=1,float yaw=0){terrain.TryGetSand(position,out var sample);var anchor=scene.CreateGameObject("Slice - "+label);anchor.Transform.WorldPosition=sample.Position;anchor.Transform.LocalScale=new(scale);anchor.Transform.EulerAngles=new(0,yaw,0);DuneWorkshop3D.Model(scene,_project!.Assets,"Assets/DesertSlice/Props/"+file+".glb",anchor,label);return anchor;}
   var garage=Prop("Service garage","garage-service-canopy",new(-12,0,10));
   void Collider(GameObject parent,string label,Vector3 center,Vector3 size){var o=scene.CreateGameObject(label);o.SetParent(parent,false);o.AddComponent(new DuneWorldObstacle3D{Center=center,Size=size});}
   foreach(float x in new[]{-7.8f,7.8f})foreach(float z in new[]{-5.8f,5.8f})Collider(garage,"Garage steel column",new(x,2.3f,z),new(.28f,4.6f,.28f));Collider(garage,"Garage roof collision",new(0,4.7f,0),new(17,.15f,13));Collider(garage,"Workshop wall collision",new(-4,1.7f,-5.95f),new(7.7f,3.4f,.2f));Collider(garage,"Workshop workbench collision",new(-4,.5f,-4.6f),new(4,1,1.2f));
   var horizon=scene.CreateGameObject("Slice - Distant sand sea");DuneWorkshop3D.Model(scene,_project!.Assets,"Assets/DesertSlice/Props/distant-sand-sea.glb",horizon,"Distant dunes");foreach(var node in Descendants(horizon))foreach(var renderer in node.Components.OfType<MeshRenderer>())renderer.CastShadows=false;
   scene.CreateGameObject("Slice - First salvage route").AddComponent(new DuneSalvageRoute3D());
   var road=scene.CreateGameObject("Slice - Haul road - editable points");road.AddComponent(new DesertRoad3D{Points=string.Join(";",points.Select(p=>p.X.ToString(CultureInfo.InvariantCulture)+","+p.Y.ToString(CultureInfo.InvariantCulture))),Width=18});
   var pad=scene.CreateGameObject("Slice - Salvage compacted apron");pad.AddComponent(new DesertRoad3D{Points=string.Join(";",Enumerable.Range(0,41).Select(i=>$"160,{-320-i*2}")),Width=80,AlbedoPath="Assets/DesertSlice/salvage-pad.png"});
   var rng=new Random(571);for(int i=0;i<14;i++){float a=i*MathF.Tau/14;var p=new Vector3(160+MathF.Sin(a)*(48+i%3*9),0,-360+MathF.Cos(a)*(48+i%4*8));var rock=Prop("Salvage perimeter rock "+i,i%4==0?"namaqualand_cliff_01":"namaqualand_boulder_02",p,i%4==0?.8f:1.3f,(float)rng.NextDouble()*360);Collider(rock,"Rock collision",new(0,.65f,0),new(2.1f,1.3f,1.8f));}
   var gantry=Prop("Salvage dismantling gantry","salvage-dismantling-gantry",new(160,0,-378));foreach(float x in new[]{-8f,8f})Collider(gantry,"Salvage gantry column",new(x,4.7f,0),new(.6f,9.4f,.6f));Collider(gantry,"Salvage store wall",new(-10,2.5f,-9),new(.15f,5,8));
   for(int i=0;i<7;i++){var p=new Vector3(138+i%3*3,0,-364+i/3*3);var crate=Prop("Salvage crate "+i,"wooden_crate_01",p,1.3f,rng.Next(-20,20));Collider(crate,"Crate collision",new(0,.6f,0),new(1.1f,1.2f,1.1f));}
   for(int i=0;i<5;i++){var drum=Prop("Salvage fuel drum "+i,"Barrel_01",new(174+i%3*1.4f,0,-368+i/3*1.5f));Collider(drum,"Drum collision",new(0,.45f,0),new(.65f,.9f,.65f));}
   for(int i=0;i<7;i++){var p=points[(i+1)*points.Length/8];for(int side=-1;side<=1;side+=2){var marker=Prop("Road shoulder marker "+i+" / "+side,"Barrel_01",new(p.X+side*13,0,p.Y),.45f);}}
   int targetIndex=0;foreach(var target in scene.GameObjects.SelectMany(o=>o.Components).OfType<DuneBountyTarget3D>().ToArray()){terrain.TryGetSand(new(155+targetIndex++*6,0,-392),out var sand);target.Transform.WorldPosition=sand.Position;foreach(var child in target.GameObject.Children.ToArray())scene.DestroyGameObject(child);DuneWorkshop3D.Model(scene,_project!.Assets,"Assets/DesertSlice/Props/Barrel_01.glb",target.GameObject,"Salvage volatile drum");}
   var wind=scene.GameObjects.FirstOrDefault(o=>o.Name=="Windblown sand");if(wind!=null){terrain.TryGetSand(new(13,0,-25),out var sand);wind.Transform.WorldPosition=sand.Position+Vector3.UnitY*.1f;}
   _project!.Scenes.Save(scene,path);Console.WriteLine("PASS Authored editable 1,024m desert, 448m road, garage and scanned salvage props");
  }
  terrain.TryGetSand(Vector3.Zero,out var packed);terrain.TryGetSand(_world?new(-1460,0,1380):new(-80,0,-80),out var loose);if(packed.Compaction<.9f||loose.Compaction>.1f||packed.Grip<=loose.Grip)throw new InvalidOperationException("Authored road packing is not applied to physical sand");
  foreach(var p in points)if(!terrain.TryGetSand(new(p.X,0,p.Y),out var sample)||sample.Normal.Y<.97f)throw new InvalidOperationException("Haul road is not smooth enough for the first contract");Console.WriteLine("PASS Road has continuous collision, gentle slopes and more grip than loose sand");
  ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.Clear();ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.PerformanceEnabled=true;ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.SandEnabled=true;
  Scenes.LoadScene(scene);var workshop=scene.GameObjects.SelectMany(o=>o.Components).OfType<DuneWorkshop3D>().Single();Tick(scene,new(.5f,.5f),false);Capture(scene,Path.Combine(root,"Preview/desert-slice-workshop.png"),false);
  if(!_prepare){
   var blueprint=Environment.GetEnvironmentVariable("DUNE_DIAGNOSTIC_VEHICLE")??Path.Combine(root,"Design/VehicleBlueprints/builds/01-dust-jackal.json");Directory.CreateDirectory(Path.Combine(root,"Saves"));File.Copy(blueprint,Path.Combine(root,"Saves/vehicle.json"),true);workshop.Command("Load vehicle");workshop.Transform.WorldPosition+=Vector3.UnitY*15;workshop.Command("Toggle drive");for(int i=0;i<12;i++)Tick(scene,new(.5f,.5f),false,Key.W);var airborneDust=scene.GameObjects.SelectMany(o=>o.Components).OfType<VfxPlayer>().Where(e=>e.GameObject.Name.StartsWith("Tyre sand plume")).ToArray();if(airborneDust.Any(e=>e.Intensity>.001f))throw new InvalidOperationException("Airborne wheels throw contact sand");Console.WriteLine("PASS Airborne wheels do not emit ground dust");workshop.Command("Recover vehicle");if(workshop.Building)throw new InvalidOperationException("Test rover did not enter drive");
   for(int i=0;i<120;i++)Tick(scene,new(.5f,.5f),false);
   var audio=scene.GameObjects.SelectMany(o=>o.Components).OfType<AudioSource3D>().Where(a=>a.GameObject.Name.StartsWith("Vehicle audio - ")).ToArray();if(audio.Length!=6||audio.Any(a=>!a.ClipLoaded))throw new InvalidOperationException("A vehicle recording failed to load");if(AudioEngine.IsAvailable&&!audio.Single(a=>a.GameObject.Name.EndsWith("engine-idle")).IsPlaying)throw new InvalidOperationException("Idle loop is silent in the native audio backend");
   var route=scene.GameObjects.SelectMany(o=>o.Components).OfType<DuneSalvageRoute3D>().Single();if(route.Arrived)throw new InvalidOperationException("Salvage arrival triggered at the garage");Console.WriteLine("PASS Route begins at garage without premature arrival");
   float idlePitch=audio.Single(a=>a.GameObject.Name.EndsWith("engine-drive")).Pitch;var start=workshop.Transform.WorldPosition;using var frameBuffer=new SceneFramebuffer();using var frameLog=new StreamWriter(Path.Combine(root,"Preview/full-driving-frames.csv"));frameLog.WriteLine("frame,update_ms,render_and_gpu_wait_ms,height,vertical_velocity,gc0");var updateTimes=new List<double>();var phaseTimes=new double[4];for(int i=0;i<240;i++){var watch=System.Diagnostics.Stopwatch.StartNew();Tick(scene,new(.5f,.5f),false,Key.W);watch.Stop();double updateMs=watch.Elapsed.TotalMilliseconds;updateTimes.Add(updateMs);watch.Restart();ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.BeginGpu();frameBuffer.RenderGame(Renderer,Renderer3D,scene,EditorMode.Play,1280,720,1280,720);double submissionMs=watch.Elapsed.TotalMilliseconds;ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.EndGpu();OpenTK.Graphics.OpenGL4.GL.Finish();ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.Frame((updateMs+watch.Elapsed.TotalMilliseconds)/1000,submissionMs,0);frameLog.WriteLine(FormattableString.Invariant($"{i},{updateMs:F3},{watch.Elapsed.TotalMilliseconds:F3},{workshop.Transform.WorldPosition.Y:F4},{workshop.PhysicalVelocity.Y:F4},{GC.CollectionCount(0)}"));phaseTimes[0]+=workshop.LastDriveCpuMilliseconds;phaseTimes[1]+=workshop.LastCameraCpuMilliseconds;phaseTimes[2]+=workshop.LastUiCpuMilliseconds;phaseTimes[3]+=workshop.LastFeedbackCpuMilliseconds;}Console.WriteLine("CPU PHASE averages drive,camera,UI,feedback: "+string.Join(",",phaseTimes.Select(v=>(v/240).ToString("0.00"))));updateTimes.Sort();Console.WriteLine($"DRIVING UPDATE median={updateTimes[120]:0.00}ms p95={updateTimes[228]:0.00}ms max={updateTimes[^1]:0.00}ms");float driven=Vector3.Distance(start,workshop.Transform.WorldPosition);if(driven<3||workshop.Transform.WorldPosition.Y<1)throw new InvalidOperationException("Rover does not drive on the exported terrain source");if(audio.Single(a=>a.GameObject.Name.EndsWith("engine-drive")).Pitch<=idlePitch+.04f)throw new InvalidOperationException("Engine pitch does not respond to load");
   var effects=scene.GameObjects.SelectMany(o=>o.Components).OfType<VfxPlayer>().Where(p=>p.GameObject.Name.StartsWith("Tyre sand plume")||p.GameObject.Name.StartsWith("Engine exhaust")).ToArray();if(!effects.Any(e=>e.GameObject.Name.StartsWith("Engine exhaust")&&e.ActiveParticles>0))throw new InvalidOperationException("Engine exhaust does not emit");if(effects.Sum(e=>e.ParticleCapacity)>1100)throw new InvalidOperationException("Vehicle particles exceed budget");
   Console.WriteLine("Particle state: "+string.Join("; ",effects.Select(e=>$"{e.GameObject.Name}={e.ActiveParticles} @ {e.Transform.WorldPosition}")));if(effects.Where(e=>e.GameObject.Name.StartsWith("Tyre sand plume")).Sum(e=>e.ActiveParticles)<40)throw new InvalidOperationException("Grounded driving does not throw sand");
   Capture(scene,Path.Combine(root,"Preview/desert-slice-driving.png"),false);
   terrain.SandShadingEnabled=false;Capture(scene,Path.Combine(root,"Preview/sand-shader-off.png"),false);terrain.SandShadingEnabled=true;Capture(scene,Path.Combine(root,"Preview/sand-shader-on.png"),false);Console.WriteLine("PASS Sand shader on/off captures produced through native renderer");for(int i=0;i<36;i++)Tick(scene,new(.5f,.5f),false,Key.W,Key.D,Key.LeftShift);Capture(scene,Path.Combine(root,"Preview/desert-slice-drift.png"),false);Console.WriteLine("PASS Native Shift drift sequence rendered / "+workshop.VehicleFeedbackDebug);for(int i=0;i<30;i++)Tick(scene,new(.5f,.5f),false,Key.Space);if(audio.Single(a=>a.GameObject.Name.EndsWith("gravel-brake")).Volume<=.01f)throw new InvalidOperationException("Braking does not produce gravel feedback");
   Console.WriteLine($"PASS Native driving {driven:0.0}m; six audio clips; load-responsive pitch; exhaust; braking; {effects.Sum(e=>e.ParticleCapacity)} particle capacity; {workshop.VehicleFeedbackDebug}; audio={AudioEngine.IsAvailable}");
   if(workshop.MissionActive){workshop.Command("Toggle drive");if(workshop.Building)throw new InvalidOperationException("Mission build lock bypassed");workshop.Command("Quit mission");workshop.Command("Return to base");}else workshop.Command("Toggle drive");Tick(scene,new(.5f,.5f),false);if(audio.Any(a=>a.IsPlaying))throw new InvalidOperationException("Vehicle sound remains active in building mode");if(scene.GameObjects.Any(o=>o.Name=="Vehicle feedback"))throw new InvalidOperationException("Vehicle effects leak when returning to build");if(!workshop.Building)throw new InvalidOperationException("Quit and return did not restore building");Console.WriteLine("PASS Mission locks building until quit and return; vehicle feedback is released");
   workshop.Command("Toggle drive");Tick(scene,new(.5f,.5f),false);var originalYard=route.SalvageYard;route.SalvageYard=workshop.Transform.WorldPosition;Tick(scene,new(.5f,.5f),false);route.CompleteMission();if(!route.Completed||route.ActiveMission)throw new InvalidOperationException("Mission completion did not resolve contract");route.ReturnToBase();Tick(scene,new(.5f,.5f),false);if(!workshop.Building)throw new InvalidOperationException("Completed contract cannot return to workshop");route.SalvageYard=originalYard;Console.WriteLine("PASS Complete mission -> return to base -> build -> redeploy loop");
  }
  if(!_prepare&&_world){
   var center=new Vector3(32,0,-32);terrain.TryGetSand(center,out var surface);center.Y=surface.Position.Y;var patch=(SandSimulationPatch3D)terrain.EnableSimulationPatch(center);float originalDepth=terrain.ContactRutDepth;terrain.ContactRutDepth=.13f;
   Vector3 prior=center+new Vector3(3.2f,0,0);
   for(int i=1;i<=320;i++){float angle=i*MathF.Tau/160;var next=center+new Vector3(MathF.Cos(angle)*3.2f,0,MathF.Sin(angle)*3.2f);terrain.TrySampleLocal(prior.X,prior.Z,out float a,out _);terrain.TrySampleLocal(next.X,next.Z,out float b,out _);prior.Y=a;next.Y=b;patch.Stamp(prior,next,1.0f,5000,3,1f/60);prior=next;}
   var reviewCamera=scene.ActiveCamera!;reviewCamera.Transform.WorldPosition=center+new Vector3(6,5,8);reviewCamera.Transform.WorldRotation=Quaternion.CreateFromRotationMatrix(Matrix4x4.Transpose(Matrix4x4.CreateLookAt(reviewCamera.Transform.WorldPosition,center,Vector3.UnitY)));Capture(scene,Path.Combine(root,"Preview/interactive-sand-surface.png"),false);terrain.ContactRutDepth=originalDepth;
   File.WriteAllText(Path.Combine(root,"Preview/console-performance-sand.txt"),ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.GetPerformanceTrace()+"\n\nSAND\n"+ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.GetSandTrace());
  }
  if(_world){var worldCamera=scene.ActiveCamera!;worldCamera.Transform.WorldPosition=new(0,3600,1200);worldCamera.Transform.WorldRotation=Quaternion.CreateFromRotationMatrix(Matrix4x4.Transpose(Matrix4x4.CreateLookAt(worldCamera.Transform.WorldPosition,Vector3.Zero,Vector3.UnitY)));Capture(scene,Path.Combine(root,"Preview/whole-map-blockout.png"),true);}
  // Representative aerial and garage view, independent of the workshop camera controller.
  var camera=scene.ActiveCamera!;camera.Transform.WorldPosition=new(105,155,90);camera.Transform.WorldRotation=Quaternion.CreateFromRotationMatrix(Matrix4x4.Transpose(Matrix4x4.CreateLookAt(camera.Transform.WorldPosition,new(70,5,-155),Vector3.UnitY)));Capture(scene,Path.Combine(root,"Preview/desert-slice-overview.png"),true);
  camera.Transform.WorldPosition=new(19,9,28);camera.Transform.WorldRotation=Quaternion.CreateFromRotationMatrix(Matrix4x4.Transpose(Matrix4x4.CreateLookAt(camera.Transform.WorldPosition,new(-8,6,8),Vector3.UnitY)));Capture(scene,Path.Combine(root,"Preview/desert-slice-garage.png"),true);
  if(_world&&terrain.Spacing==8){var savedPosition=camera.Transform.WorldPosition;camera.Transform.WorldPosition=new(170,25,-170);camera.Transform.WorldRotation=Quaternion.CreateFromRotationMatrix(Matrix4x4.Transpose(Matrix4x4.CreateLookAt(camera.Transform.WorldPosition,new(-620,8,-700),Vector3.UnitY)));Capture(scene,Path.Combine(root,"Preview/wide-desert-ground-view.png"),true);}
  camera.Transform.WorldPosition=_world&&terrain.Spacing==8?new(428,13,-863):new(188,13,-323);camera.Transform.WorldRotation=Quaternion.CreateFromRotationMatrix(Matrix4x4.Transpose(Matrix4x4.CreateLookAt(camera.Transform.WorldPosition,_world&&terrain.Spacing==8?new(398,6,-903):new(158,6,-363),Vector3.UnitY)));Capture(scene,Path.Combine(root,"Preview/desert-slice-salvage.png"),true);
  using(var fb=new ByteEngine.Editor.SceneFramebuffer()){
   var env=scene.GameObjects.SelectMany(o=>o.Components).OfType<SkyEnvironment>().Single();var oldQuality=env.Quality;var oldAo=env.AmbientOcclusion;var oldBloom=env.Bloom;var variants=new List<object>();
   foreach(var variant in new[]{(false,GraphicsQuality.Balanced),(true,GraphicsQuality.Balanced),(true,GraphicsQuality.Fast),(false,GraphicsQuality.Fast)}){
    terrain.UseDistanceLod=variant.Item1;env.Quality=variant.Item2;if(variant.Item2!=GraphicsQuality.Fast){env.AmbientOcclusion=.18f;env.Bloom=.025f;}
    var timings=new List<double>();for(int i=0;i<24;i++){var watch=System.Diagnostics.Stopwatch.StartNew();fb.Render(Renderer,Renderer3D,scene,ByteEngine.Editor.EditorMode.Play,new ByteEngine.Editor.EditorCamera(),EditCamera(scene.ActiveCamera!),true,1280,720,1280,720,drawGrid3D:false);OpenTK.Graphics.OpenGL4.GL.Finish();watch.Stop();if(i>=4)timings.Add(watch.Elapsed.TotalMilliseconds);}
    timings.Sort();Console.WriteLine($"RENDER BENCHMARK 1280x720 {variant.Item2} / LOD={variant.Item1}: median={timings[10]:0.0}ms; p95={timings[18]:0.0}ms; approximate ceiling={1000/timings[10]:0.0}fps (render only)");variants.Add(new{lod=variant.Item1,quality=variant.Item2.ToString(),medianMilliseconds=timings[10],p95Milliseconds=timings[18]});
   }
   env.Quality=oldQuality;env.AmbientOcclusion=oldAo;env.Bloom=oldBloom;terrain.UseDistanceLod=true;File.WriteAllText(Path.Combine(root,"Preview/desert-render-benchmark.json"),JsonSerializer.Serialize(new{width=1280,height=720,variants,renderOnly=true}));
  }
  Scenes.UnloadScene();_project!.Dispose();Console.WriteLine("DESERT SLICE VALIDATION COMPLETE");Close();
 }
}
