using System.Numerics;
using System.Text.Json;
using System.IO.Compression;
using OpenTK.Graphics.OpenGL4;
using ByteEngine.Core.Graphics;
using ByteEngine.Core.Graphics.ThreeD;
using DesertTerrain;
using ByteEngine.Core;
using ByteEngine.Core.Plugins;
using ByteEngine.Core.Scene;
using ByteEngine.Editor;
using DuneCompany;
namespace ByteEngine.Tests;
internal sealed class DuneWorkshopDiagnostic:ByteEngineApplication
{
 readonly string _file;EditorProjectContext? _project;
 public DuneWorkshopDiagnostic(string file):base(1280,720,"Dune Company workshop validation"){_file=Path.GetFullPath(file);IsVisible=false;}
 protected override bool ShouldUpdateScene=>false;protected override bool ShouldRenderSceneToWindow=>false;
 protected override void OnEngineStart()
 {
  var root=Path.GetDirectoryName(_file)!;Directory.CreateDirectory(Path.Combine(root,"Preview"));var package=Path.GetFullPath("artifacts/plugins/DuneCompany.byteplugin");var installed=ByteEnginePluginPackageManager.ListInstalled(root).FirstOrDefault(p=>p.Id=="bytebard.dunecompany");if(installed?.PackagePath is {} existing)File.Copy(package,existing,true);else Console.WriteLine(ByteEnginePluginPackageManager.Import(root,package).Message);
  _project=EditorProjectContext.Open(_file,m=>Console.WriteLine("WARNING: "+m));Check(_project.IsPluginLoaded("bytebard.dunecompany"),"Workshop plugin imports");
  var path=Path.Combine(root,_project.Project.StartupScene);var scene=_project.Scenes.Load(path);var terrain=scene.GameObjects.SelectMany(o=>o.Components).Single(c=>c.GetType().FullName=="DesertTerrain.DesertTerrain3D");
  if(!scene.GameObjects.Any(o=>o.GetComponent<DuneBountyTarget3D>()!=null))for(int i=0;i<3;i++){var target=scene.CreateGameObject("Contract target "+(i+1));var point=new Vector3((i-1)*12,0,-22-i*10);object?[] sampleArgs=[point,null];terrain.GetType().GetMethod("TryGetSand")!.Invoke(terrain,sampleArgs);target.Transform.WorldPosition=(Vector3)sampleArgs[1]!.GetType().GetProperty("Position")!.GetValue(sampleArgs[1])!;target.AddComponent(new DuneBountyTarget3D());var visual=scene.CreateGameObject("Armoured fuel cache");visual.SetParent(target,false);visual.Transform.LocalPosition=new(0,.75f,0);visual.Transform.LocalScale=new(1.8f,1.5f,1.8f);visual.AddComponent(new MeshRenderer{UsePrimitive=true,Primitive=PrimitiveMeshType.Cube,Material=new(){BaseColor=new(.4f,.12f,.06f,1)},CastShadows=false});}
  foreach(var target in scene.GameObjects.Where(o=>o.Name=="Armoured fuel cache"))target.GetComponent<MeshRenderer>()!.UsePrimitive=true;foreach(var sun in scene.GameObjects.SelectMany(o=>o.Components).OfType<DirectionalLight>())sun.CastShadows=true;
  Scenes.LoadScene(scene);var workshop=scene.GameObjects.SelectMany(o=>o.Components).OfType<DuneWorkshop3D>().Single();
  Check(workshop.Catalog.Count==31,"All approved part definitions load");foreach(var part in workshop.Catalog.Values)_project.Assets.LoadModel(new(part.File));Check(workshop.GameObject.Children.Count>0,"Native part mesh hierarchy is visible");
  var camera=scene.ActiveCamera!;var cameraStart=camera.Transform.WorldPosition;Tick(scene,new(.45f,.45f),false);OrbitTick(scene,new(.45f,.45f));OrbitTick(scene,new(.40f,.50f));Check(Vector3.Distance(cameraStart,camera.Transform.WorldPosition)>.5f,"Middle-button drag orbits the camera");Tick(scene,new(.5f,.5f),false);var keyboardStart=camera.Transform.WorldPosition;Tick(scene,new(.5f,.5f),false,Key.J);Check(Vector3.Distance(keyboardStart,camera.Transform.WorldPosition)>.01f,"Keyboard camera orbit works without cursor capture");Check(Input.KeepGameViewPointerFree,"Workshop requests a free cursor in the editor");
  var snap=DuneWorkshop3D.SnapFace(new(.25f,.26f,.17f),Vector3.UnitX,new(-.25f,0,-.5f),new(.25f,.5f,.5f));Check(Vector3.Distance(snap,new(.25f,.25f,0))<.001f,"Side mounts snap to the beam centre height");
  int priorMouse=workshop.Blocks.Count;var top=workshop.Transform.WorldPosition+Vector3.UnitY*.5f;Tick(scene,Pointer(scene.ActiveCamera!,top),false);Tick(scene,Pointer(scene.ActiveCamera!,top),true);Check(workshop.Blocks.Count==priorMouse+1,"Game View mouse click places a block on a free surface");Tick(scene,new(.5f,.5f),false);workshop.Command("Undo");
  var sidePoint=workshop.Transform.WorldPosition+new Vector3(.25f,.25f,0);Tick(scene,Pointer(scene.ActiveCamera!,sidePoint),false);Tick(scene,Pointer(scene.ActiveCamera!,sidePoint),true);Check(workshop.Blocks.Count==priorMouse+1&&Math.Abs(workshop.Blocks.Last().P.Y)<.001f,"Side-attached beams keep their base heights aligned");Tick(scene,new(.5f,.5f),false);workshop.Command("Undo");Tick(scene,new(.5f,.5f),false,Key.R);Tick(scene,Pointer(scene.ActiveCamera!,sidePoint),false);Tick(scene,Pointer(scene.ActiveCamera!,sidePoint),true);Check(workshop.Blocks.Count==priorMouse+1&&Math.Abs(Vector3.Transform(Vector3.UnitZ,workshop.Blocks.Last().Q).X)>.99f,"R places a beam crosswise on a side face");Tick(scene,new(.5f,.5f),false);workshop.Command("Undo");
  // Place a real tyre through the palette and pointer; test its rendered vertices, not just the catalogue.
  Tick(scene,new(69f/1280,665f/720),true);Tick(scene,Pointer(camera,sidePoint),false);Tick(scene,Pointer(camera,sidePoint),false);Tick(scene,Pointer(camera,sidePoint),true);var placedTyre=workshop.Blocks.Last();Console.WriteLine("TYRE "+placedTyre.Type+" / "+scene.GameObjects.Single(o=>o.Name=="Placement instruction").GetComponent<UiText>()!.Text);Capture(scene,Path.Combine(root,"Preview/tyre-pick.png"),true);Check(placedTyre.Type==13,"Wheel palette places the actual tyre");var tyreObject=workshop.GameObject.Children.Single(o=>o.GetComponent<DuneBlock3D>()?.BlockId==placedTyre.Id);float inner=GeometryPoints(tyreObject).Min(v=>v.X);Check(inner>=workshop.Transform.WorldPosition.X+.25f+.005f,"Rendered tyre is outside the mounting block");Capture(scene,Path.Combine(root,"Preview/tyre-clearance.png"),true);Tick(scene,new(.5f,.5f),false);workshop.Command("Undo");Tick(scene,new(833f/1280,24f/720),true);Tick(scene,Pointer(camera,sidePoint),false);Check(workshop.HighlightedBlock==0,"Tune hover highlights the picked block");Capture(scene,Path.Combine(root,"Preview/tune-hover.png"),true);Tick(scene,new(.5f,.5f),false,Key.Escape);Tick(scene,new(28f/1280,665f/720),true);Tick(scene,new(.5f,.5f),false);
  Tick(scene,new(153f/1280,665f/720),true);for(int i=0;i<90;i++)Tick(scene,new(.5f,.5f),false,Key.K);var under=workshop.Transform.WorldPosition;Tick(scene,Pointer(camera,under),false);Tick(scene,Pointer(camera,under),true);var suspension=workshop.Blocks.Last();var suspensionDef=workshop.PhysicsDefinition(16);Console.WriteLine("SUSPENSION BOUNDS "+suspensionDef);Check(suspension.Type==16&&Math.Abs(suspension.P.Y+suspensionDef.Fixed.High.Y)<.04f&&Vector3.Transform(Vector3.UnitY,suspension.Q).Y>.99f,"Suspension mounts by its fixed top end below the frame");Tick(scene,new(.5f,.5f),false);Tick(scene,new(69f/1280,665f/720),true);var outPoint=workshop.Transform.WorldPosition+suspension.P+new Vector3(suspensionDef.Moving.High.X,suspensionDef.Pivot.Y,0);Tick(scene,Pointer(camera,outPoint),false);Tick(scene,Pointer(camera,outPoint),false);Tick(scene,Pointer(camera,outPoint),true);Console.WriteLine("SUSPENSION WHEEL "+scene.GameObjects.Single(o=>o.Name=="Placement instruction").GetComponent<UiText>()!.Text);Check(workshop.Blocks.Last().Type==13&&workshop.Blocks.Last().Parent==suspension.Id&&workshop.Blocks.Last().MovingMount,"Tyre attaches to the suspension moving output");Capture(scene,Path.Combine(root,"Preview/suspension-mount.png"),true);Tick(scene,new(.5f,.5f),false);workshop.Command("Undo");workshop.Command("Undo");for(int i=0;i<90;i++)Tick(scene,new(.5f,.5f),false,Key.I);Tick(scene,new(28f/1280,665f/720),true);Tick(scene,new(.5f,.5f),false);
  var compact=workshop.Catalog[23];Check(!workshop.HasMountSupport(23,new(0,.5f-compact.Low.Y,0),Quaternion.Identity,-Vector3.UnitY,0),"Compact engine rejects an undersized short rail");
  int prior=workshop.Blocks.Count;Check(workshop.AddBlock(3,0,new(0,.5f,0),Quaternion.Identity),"A free structural block can be placed");workshop.Command("Undo");Check(workshop.Blocks.Count==prior,"Undo restores the build");workshop.Command("Redo");Check(workshop.Blocks.Count==prior+1,"Redo restores the edit");var preserved=workshop.Blocks.Last().P;workshop.AddBlock(1,1,new(1,.5f,0),Quaternion.Identity);Check(workshop.RemoveBlock(0)&&workshop.Blocks.Count==2&&workshop.Blocks.Any(b=>b.Id==0&&b.Type==3&&b.Parent==-1&&Vector3.Distance(b.P,preserved)<.001f),"Starting block can be deleted without moving or deleting the rest");BuildStore.Read(workshop.BuildJson,workshop.Catalog);workshop.Command("Undo");workshop.Command("Undo");Check(workshop.HasMountSupport(23,new(0,1-compact.Low.Y,0),Quaternion.Identity,-Vector3.UnitY,1),"A deck supports the compact engine footprint");var cab=workshop.Catalog[26];Check(!workshop.HasMountSupport(26,new(.5f,1-cab.Low.Y,0),Quaternion.Identity,-Vector3.UnitY,1),"An armoured cab rejects insufficient deck width");workshop.AddBlock(3,0,new(1,.5f,0),Quaternion.Identity);Check(workshop.HasMountSupport(26,new(.5f,1-cab.Low.Y,0),Quaternion.Identity,-Vector3.UnitY,1),"Adjacent deck blocks combine into a valid cab base");workshop.Command("Undo");
  workshop.AddBlock(23,1,new(0,1,.55f),Quaternion.Identity);workshop.AddBlock(25,1,new(0,1,-.6f),Quaternion.Identity);
  foreach(int x in new[]{-1,1})foreach(int z in new[]{-1,1})workshop.AddBlock(13,1,new(x*.9f,-.15f,z*.72f),Quaternion.CreateFromAxisAngle(Vector3.UnitY,-x*MathF.PI*.5f));
  var wheel=workshop.Blocks.Last();workshop.Command("Tune selected");Tick(scene,new(1000f/1280,166f/720),true);Tick(scene,new(1200f/1280,166f/720),true);Tick(scene,new(1200f/1280,166f/720),false);Check(wheel.Power>1.5f,"Tuning slider follows a held mouse drag");Tick(scene,new(1200f/1280,140f/720),true);Tick(scene,new(1200f/1280,140f/720),false,Key.D1);Tick(scene,new(1200f/1280,140f/720),false,Key.Enter);Check(Math.Abs(wheel.Power-1)<.001f,"Typed tuning value applies with Enter");Tick(scene,new(.5f,.5f),false,Key.Escape);
  workshop.AddBlock(30,1,new(0,1.2f,-1.2f),Quaternion.Identity);
  var before=workshop.Blocks.Select(b=>(b.Id,b.P,b.Q)).ToArray();workshop.Command("Save vehicle");string saved=File.ReadAllText(Path.Combine(root,"Saves/vehicle.json"));File.WriteAllText(Path.Combine(root,"Saves/ScoutBuggy.json"),saved);workshop.RemoveBlock(workshop.Blocks.Last().Id);workshop.Command("Load vehicle");Check(workshop.Blocks.Count==before.Length,"Vehicle save/load preserves every block");
  var startingTargets=scene.GameObjects.SelectMany(o=>o.Components).OfType<DuneBountyTarget3D>().ToArray();var testTarget=startingTargets[0];var priorTargetPosition=testTarget.Transform.WorldPosition;testTarget.Transform.WorldPosition=workshop.Transform.WorldPosition+new Vector3(0,.5f,-8);
  var start=workshop.Transform.WorldPosition;workshop.Command("Toggle drive");Check(!workshop.Building,"Seat, engine and wheels unlock driving");Check(workshop.FireWeapon(false)&&testTarget.Health<100,"Mounted gun hits and damages a contract target");testTarget.ResetTarget();testTarget.Transform.WorldPosition=priorTargetPosition;for(int i=0;i<150;i++){workshop.StepDrive(1,0,false,1f/60);if(workshop.Blocks.Where(b=>workshop.Catalog[b.Type].Wheel).Any(b=>workshop.RenderedWheelAxisError(b.Id)>.1f))throw new InvalidOperationException("Rendered tyre axis diverges at frame "+i+": "+string.Join(" / ",workshop.Blocks.Where(b=>workshop.Catalog[b.Type].Wheel).Select(b=>$"{b.Id}: rendered={workshop.RenderedWheelAxisError(b.Id)} physical={workshop.WheelAxisError(b.Id)}")));}Check(true,"Visible tyre axes remain aligned through every driving frame");Console.WriteLine("NATIVE DRIVE distance="+Vector3.Distance(start,workshop.Transform.WorldPosition)+" / "+workshop.PhysicsDebug);Capture(scene,Path.Combine(root,"Preview/physical-driving-probe.png"),false);Check(Vector3.Distance(start,workshop.Transform.WorldPosition)>6,"Engine power moves the actual assembled vehicle");Directory.CreateDirectory(Path.Combine(root,"Preview"));Capture(scene,Path.Combine(root,"Preview/scout-driving.png"),false);float speed=workshop.Speed;for(int i=0;i<180;i++)workshop.StepDrive(0,0,true,1f/60);Console.WriteLine($"NATIVE BRAKE before={speed} after={workshop.Speed} velocity={workshop.PhysicalVelocity}");Check(Math.Abs(workshop.Speed)<Math.Abs(speed)*.2f,"Ground-contact braking slows the vehicle");
  var heading=workshop.Transform.WorldRotation;for(int i=0;i<50;i++)workshop.StepDrive(1,1,false,1f/60);Check(workshop.Blocks.Where(b=>workshop.Catalog[b.Type].Wheel).All(b=>!workshop.HasSteeringConnection(b.Id)&&workshop.WheelAxisError(b.Id)<.5f),"Wheels without a steering hinge retain fixed axles");
  workshop.Command("Toggle drive");foreach(var b in workshop.Blocks)Check(before.Any(a=>a.Id==b.Id&&Vector3.Distance(a.P,b.P)<.0001f&&Math.Abs(Quaternion.Dot(a.Q,b.Q))>.9999f),"Build/drive preserves block pose "+b.Id);
  workshop.AddBlock(18,1,new(0,0,-.72f),Quaternion.Identity);int hinge=workshop.Blocks.Last().Id;foreach(var front in workshop.Blocks.Where(b=>workshop.Catalog[b.Type].Wheel&&b.P.Z<0).ToArray())Check(workshop.ReparentBlock(front.Id,hinge,true),"Front wheel connects to steering output");workshop.Command("Toggle drive");var hingeHeading=workshop.Transform.WorldRotation;for(int i=0;i<45;i++){Tick(scene,new(.5f,.5f),false,Key.W,Key.D);CheckRenderedAxles(workshop);}Check(Math.Abs(Quaternion.Dot(hingeHeading,workshop.Transform.WorldRotation))<.999f,"Connected steering hinge turns the vehicle");for(int i=0;i<90;i++)Tick(scene,new(.5f,.5f),false);var behind=workshop.CameraPosition-workshop.Transform.WorldPosition;behind.Y=0;var f=workshop.Transform.Forward;f.Y=0;Check(Vector3.Dot(Vector3.Normalize(behind),Vector3.Normalize(f))<-.7f,"Chase camera recentres behind the vehicle automatically");Capture(scene,Path.Combine(root,"Preview/chase-camera.png"),false);workshop.Command("Toggle drive");
  workshop.AddBlock(21,0,new(3,0,0),Quaternion.Identity);int piston=workshop.Blocks.Last().Id;workshop.AddBlock(1,piston,new(3,.3f,-1.2f),Quaternion.Identity,true);int output=workshop.Blocks.Last().Id;var outputBefore=workshop.GameObject.Children.Single(o=>o.GetComponent<DuneBlock3D>()?.BlockId==output).Transform.LocalPosition;workshop.Command("Toggle drive");for(int i=0;i<40;i++)Tick(scene,new(.5f,.5f),false,Key.E);var outputAfter=workshop.GameObject.Children.Single(o=>o.GetComponent<DuneBlock3D>()?.BlockId==output).Transform.LocalPosition;Check(Vector3.Distance(outputBefore,outputAfter)>.35f,"Piston actuation carries its attached output block");workshop.Command("Toggle drive");
  // Save an optional working example, but author the scene with a single starting block.
  while(workshop.Blocks.Count>1)workshop.RemoveBlock(workshop.Blocks[1].Id);workshop.Command("Save vehicle");Directory.CreateDirectory(Path.Combine(root,"Preview"));Capture(scene,Path.Combine(root,"Preview/workshop-editor.png"),true);_project.Scenes.Save(scene,path);var restored=_project.Scenes.Load(path);Check(restored.GameObjects.Any(o=>o.GetComponent<DuneBlock3D>()?.BlockId==0),"Scene save contains editable model objects");Check(restored.GameObjects.Count(o=>o.GetComponent<ByteEngine.Core.Graphics.UiWidget>()!=null)>50,"Native authored workshop UI survives reload");
  Directory.CreateDirectory(Path.Combine(root,"Preview"));File.WriteAllText(Path.Combine(root,"Preview/workshop-validation.json"),JsonSerializer.Serialize(new{parts=31,checks="plugin import, 31 models, native mouse placement, undo/redo, slider drag, numeric entry, save/load, gun hit, drive, brake, steering, piston output, build/play poses, authored scene roundtrip",limitations="Rigid wheel-contact prototype; articulated mechanics and realistic combat physics not yet finished"},new JsonSerializerOptions{WriteIndented=true}));
  foreach(var o in restored.GameObjects.ToArray())restored.DestroyGameObject(o);Scenes.UnloadScene();_project.Dispose();Console.WriteLine("Dune workshop validation passed.");Close();
 }
    private static EditorCamera3D EditCamera(Camera3D c){var f=c.Transform.Forward;return new(){Position=c.Transform.WorldPosition,Yaw=MathF.Atan2(f.Z,f.X)*180/MathF.PI,Pitch=MathF.Asin(f.Y)*180/MathF.PI,FieldOfView=c.FieldOfView};}
    private void Capture(Scene scene,string file,bool edit)
    {
        using var fb=new SceneFramebuffer();fb.Render(Renderer,Renderer3D,scene,edit?EditorMode.Edit:EditorMode.Play,new EditorCamera(),EditCamera(scene.ActiveCamera!),true,1280,720,1280,720,drawGrid3D:false);GL.Finish();var pixels=new byte[1280*720*4];GL.BindTexture(TextureTarget.Texture2D,(int)fb.TextureId);GL.GetTexImage(TextureTarget.Texture2D,0,PixelFormat.Rgba,PixelType.UnsignedByte,pixels);GL.BindTexture(TextureTarget.Texture2D,0);
        DesertTerrainTests.Check(GL.GetError()==ErrorCode.NoError,"Native terrain renders without OpenGL errors");Png(file,pixels,1280,720);
    }
    private static void Png(string file,byte[] rgba,int width,int height)
    {
        using var output=File.Create(file);output.Write(new byte[]{137,80,78,71,13,10,26,10});byte[] header=new byte[13];System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(header.AsSpan(0,4),width);System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(header.AsSpan(4,4),height);header[8]=8;header[9]=6;Chunk(output,"IHDR",header);
        using var compressed=new MemoryStream();using(var z=new ZLibStream(compressed,CompressionLevel.Fastest,true))for(int y=height-1;y>=0;y--){z.WriteByte(0);z.Write(rgba,y*width*4,width*4);}Chunk(output,"IDAT",compressed.ToArray());Chunk(output,"IEND",[]);
    }
    private static void Chunk(Stream s,string type,byte[] data)
    {
        byte[] name=System.Text.Encoding.ASCII.GetBytes(type),length=new byte[4];System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(length,data.Length);s.Write(length);s.Write(name);s.Write(data);uint crc=0xffffffff;foreach(byte b in name.Concat(data)){crc^=b;for(int i=0;i<8;i++)crc=(crc>>1)^((crc&1)==1?0xedb88320u:0);}System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(length,~crc);s.Write(length);
    }
 static Vector2 Pointer(Camera3D camera,Vector3 point){var view=Vector4.Transform(new Vector4(point,1),camera.GetViewMatrix());var clip=Vector4.Transform(view,camera.GetProjectionMatrix(1280f/720));return new((clip.X/clip.W+1)*.5f,(1-clip.Y/clip.W)*.5f);}
 static void Tick(Scene scene,Vector2 pointer,bool mouse,params Key[] keys){var raw=new ByteEngine.Core.InputSystem.RawInputSnapshot();raw.KeysDown.UnionWith(keys);if(mouse)raw.MouseButtonsDown.Add(MouseButton.Left);Input.UpdatePortable(raw,false);Input.SetGameViewPointer(pointer,new(1280,720),true);Time.Update(1f/60);scene.UpdateInternal();}
 static void OrbitTick(Scene scene,Vector2 pointer){var raw=new ByteEngine.Core.InputSystem.RawInputSnapshot();raw.MouseButtonsDown.Add(MouseButton.Middle);Input.UpdatePortable(raw,false);Input.SetGameViewPointer(pointer,new(1280,720),true);Time.Update(1f/60);scene.UpdateInternal();}
 static IEnumerable<Vector3> GeometryPoints(GameObject root){foreach(var c in root.Children){foreach(var point in GeometryPoints(c))yield return point;}foreach(var renderer in root.Components.OfType<MeshRenderer>()){if(renderer.Mesh==null)continue;var vertices=renderer.Mesh.VertexData.ToArray();for(int i=0;i<vertices.Length;i+=8)yield return Vector3.Transform(new Vector3(vertices[i],vertices[i+1],vertices[i+2]),root.Transform.WorldMatrix);}}
 static void CheckRenderedAxles(DuneWorkshop3D workshop){foreach(var b in workshop.Blocks.Where(b=>workshop.Catalog[b.Type].Wheel))if(workshop.RenderedWheelAxisError(b.Id)>.1f)throw new InvalidOperationException("Rendered wheel diverges during steering: "+b.Id);}
 static void Check(bool ok,string message){if(!ok)throw new InvalidOperationException(message);Console.WriteLine("PASS "+message);}
}
