using System.Numerics;
using ByteEngine.Core.Assets;
using ByteEngine.Core.Characters;
using ByteEngine.Core.Audio;
using ByteEngine.Core.Graphics;
using ByteEngine.Core.Physics;
using ByteEngine.Core.Runtime;
using ByteEngine.Core.Scene;
using ByteEngine.Core.Serialization;
namespace ByteEngine.Tests;
internal static class EngineFoundationTests
{
 public static void Run(string root)
 {
  void Check(bool condition,string message){if(!condition)throw new Exception(message);}
  foreach(int rate in new[]{30,60,144}){var clock=new FixedStepClock();int ticks=0;double position=0,velocity=0;for(int i=0;i<rate*10;i++)clock.Advance(1d/rate,dt=>{ticks++;velocity+=2*dt;position+=velocity*dt;});Check(ticks==600&&Math.Abs(position-100.1666667)<1e-5,"Fixed trajectories changed with render rate");}
  var bounded=new FixedStepClock();Check(bounded.Advance(10,_=>{})==8&&bounded.DroppedSeconds>9,"Suspended tab causes unbounded catch-up");Check(bounded.InterpolationAlpha is >=0 and <=1,"Interpolation out of bounds");bounded.Reset();Check(bounded.DroppedSeconds==0,"Clock reset");
  var scene=new Scene("Responsive UI");var canvas=scene.CreateGameObject("Canvas");canvas.AddComponent(new UiCanvas());var panel=scene.CreateGameObject("Panel");panel.SetParent(canvas,false);panel.AddComponent(new UiWidget{Offset=Vector2.Zero,Size=new(400,300)});var layout=panel.AddComponent(new UiContainer{Padding=new(10),Spacing=new(8),EqualWidth=true});var a=scene.CreateGameObject("A");a.SetParent(panel,false);var aw=a.AddComponent(new UiWidget{Offset=new(99,98),Size=new(100,40)});var b=scene.CreateGameObject("B");b.SetParent(panel,false);var bw=b.AddComponent(new UiWidget{Size=new(100,40)});
  var first=UiLayout.Resolve(a,aw.Anchor,aw.Offset,aw.Size,new(1280,720));var second=UiLayout.Resolve(b,bw.Anchor,bw.Offset,bw.Size,new(1280,720));Check(first.Position==new Vector2(10)&&first.Size==new Vector2(380,40)&&second.Position==new Vector2(10,58),"Column layout");Check(aw.Offset==new Vector2(99,98),"Layout rewrites authored offsets");a.Active=false;Check(UiLayout.Resolve(b,bw.Anchor,bw.Offset,bw.Size,new(1280,720)).Position==new Vector2(10),"Hidden child consumes space");a.Active=true;layout.Kind=UiContainerKind.Grid;layout.CellSize=new(150,60);Check(UiLayout.Resolve(b,bw.Anchor,bw.Offset,bw.Size,new(1280,720)).Position==new Vector2(168,10),"Wide grid");panel.GetComponent<UiWidget>()!.Size=new(180,300);Check(UiLayout.Resolve(b,bw.Anchor,bw.Offset,bw.Size,new(1280,720)).Position==new Vector2(10,78),"Grid does not reflow");layout.Kind=UiContainerKind.Row;Check(UiLayout.Resolve(b,bw.Anchor,bw.Offset,bw.Size,new(640,360)).Position==new Vector2(59,5),"Scaled row hit-test/render coordinates differ");
  AudioMixer.Reset();AudioMixer.SetVolume(AudioBus.Master,.5f);AudioMixer.SetVolume(AudioBus.Music,.4f);Check(Math.Abs(new AudioSource3D{Bus=AudioBus.Music,Volume=.8f}.EffectiveVolume-.16f)<.0001,"Bus gains");AudioMixer.SetVolume(AudioBus.Ui,0);Check(new AudioSource3D{Bus=AudioBus.Ui}.EffectiveVolume==0,"UI mute");Check(new AudioSource3D{Bus=AudioBus.Sfx}.EffectiveVolume==.5f,"Music mute affected effects");AudioMixer.SetVolume(AudioBus.Music,2);Check(AudioMixer.GetVolume(AudioBus.Music)==1,"Gain clamp");bool invalid=false;try{AudioMixer.GetVolume((AudioBus)999);}catch(ArgumentOutOfRangeException){invalid=true;}Check(invalid,"Invalid bus crashes outside validation");AudioMixer.Reset();
  string assetsPath=Path.Combine(root,"foundation-assets");Directory.CreateDirectory(Path.Combine(assetsPath,"Assets"));File.WriteAllText(Path.Combine(assetsPath,"Assets/a.txt"),"one");File.WriteAllText(Path.Combine(assetsPath,"Assets/b.txt"),"two");using var database=new AssetDatabase(assetsPath,["Assets"]);var id=database.Assets.Single(r=>r.ProjectPath=="Assets/a.txt").Guid;File.WriteAllText(Path.Combine(assetsPath,"Assets/a.txt"),"changed");database.RefreshPaths(["Assets/a.txt"]);Check(!database.LastRefreshWasFullScan&&database.LastRefreshFileCount==1&&database.Resolve(new AssetReference(id))!=null,"Single asset change triggers full import or loses identity");File.Delete(Path.Combine(assetsPath,"Assets/a.txt"));database.RefreshPaths(["Assets/a.txt"]);Check(database.Resolve(new AssetReference(id))==null,"Deleted asset remains indexed");
  using var manager=new AssetManager(database);var serializer=new ComponentSerializer(assetsPath,database,manager,null);AudioSerializationRegistrar.Register(serializer);var restored=(UiContainer)serializer.Deserialize(serializer.Serialize(layout)!)!;Check(restored.Kind==layout.Kind&&restored.Padding==layout.Padding&&restored.CellSize==layout.CellSize,"Container roundtrip");var sound=(AudioSource3D)serializer.Deserialize(serializer.Serialize(new AudioSource3D{Bus=AudioBus.Ui,Volume=.3f})!)!;Check(sound.Bus==AudioBus.Ui&&sound.Volume==.3f,"Audio bus roundtrip");
  var sparse=new Scene("Sparse colliders");for(int i=0;i<5000;i++){var obj=sparse.CreateGameObject("Collider");obj.Transform.LocalPosition=new(i*3,0,0);obj.AddComponent(new BoxCollider3D());}sparse.Physics.Step(sparse,1f/60);Check(sparse.Physics.LastColliderCount==5000&&sparse.Physics.LastCandidateCount==0,"Sparse broadphase enumerates separated pairs");
  var grid=new ByteEngine.Core.Navigation.NavigationGrid(7,7);for(int z=0;z<6;z++)grid.SetCell(3,z,true);var route=grid.FindPath(new(.5f,0,.5f),new(6.5f,0,.5f));Check(route.Count>0&&route.Any(point=>point.Z>=6),"Navigation crossed blocked wall");grid.SetCell(3,6,true);Check(grid.FindPath(new(.5f,0,.5f),new(6.5f,0,.5f)).Count==0,"Unreachable path returned");var corner=new ByteEngine.Core.Navigation.NavigationGrid(2,2);corner.SetCell(1,0,true);corner.SetCell(0,1,true);Check(corner.FindPath(new(.5f,0,.5f),new(1.5f,0,1.5f)).Count==0,"Diagonal cuts obstacle corner");
  var lod=new ByteEngine.Core.Graphics.ThreeD.MeshLodGroup();Check(lod.SelectLevel(10)==0&&lod.SelectLevel(30)==1&&lod.SelectLevel(100)==2,"LOD thresholds");lod.CullDistance=150;Check(lod.SelectLevel(151)==-1,"LOD cull");
  var palette=canvas.AddComponent(new UiTheme());aw.ThemeKey="primary";Check(UiTheme.Find(a)==palette&&palette.Background("primary",true,false,false)==palette.Primary,"Inherited theme");Check(palette.Background("primary",false,true,false)==palette.Disabled,"Disabled theme");var widgetCopy=(UiWidget)serializer.Deserialize(serializer.Serialize(aw)!)!;Check(widgetCopy.ThemeKey=="primary","Widget theme serialization");
  Console.WriteLine("PASS fixed cadence at 30/60/144 FPS, bounded catch-up, responsive row/column/grid, visibility/scaling, bus gains/mute/serialization, incremental file refresh/delete, 5,000 sparse collider broadphase, obstacle-aware A* and no corner cutting, LOD selection/cull, inherited themes.");
 }
}
