using ByteEngine.Core;
using ByteEngine.Core.Scene;
using ByteEngine.Core.Variables;
using ByteEngine.Core.VisualLogic;
namespace ByteEngine.Tests;
internal static class SceneNavigationTests
{
 public static void Run(){var manager=new SceneManager();var initial=new Scene("Menu");var owner=initial.CreateGameObject("Events");manager.LoadScene(initial);int loads=0;manager.GlobalVariables.Set("Carry",VariableValue.FromNumber(7));manager.SceneFactory=path=>{loads++;if(path=="Scenes/Missing.bytescene")throw new FileNotFoundException(path);return new Scene(path);};var registry=VisualLogicRegistry.CreateDefault();if(!registry.TryGetAction("scene.load",out var action))throw new Exception("Missing load action");action!.Execute(new(){Id="scene.load",Arguments=new(){["path"]=EventValue.String("Scenes/Game.bytescene")}},new(){Scene=initial,Self=owner,Globals=manager.GlobalVariables});if(manager.ActiveScene!=initial||loads!=0)throw new Exception("Scene load was not deferred");Time.Update(1f/60);manager.UpdateInternal();if(manager.ActiveScene?.Name!="Scenes/Game.bytescene"||loads!=1)throw new Exception("Deferred scene transition failed");var active=manager.ActiveScene;active!.RequestLoad("Scenes/Missing.bytescene");Time.Update(1f/60);manager.UpdateInternal();if(manager.ActiveScene!=active)throw new Exception("Failed load discarded the working scene");foreach(string path in new[]{"../Other.bytescene","C:/Other.bytescene","Scenes/file.txt"}){bool rejected=false;try{active.RequestLoad(path);}catch(ArgumentException){rejected=true;}if(!rejected)throw new Exception("Unsafe scene path accepted");}bool quit=false;manager.QuitHandler=()=>quit=true;active.RequestQuit();Time.Update(1f/60);manager.UpdateInternal();if(!quit)throw new Exception("Quit handler not called");manager.ShowLoadingScreen=true;active.RequestLoad("Scenes/Next.bytescene");Time.Update(1f/60);manager.UpdateInternal();if(manager.ActiveScene!=active||!active.LoadingScreenVisible)throw new Exception("Loading frame was skipped");Time.Update(1f/60);manager.UpdateInternal();if(manager.ActiveScene!=active)throw new Exception("Scene loaded before loading screen presentation");active.LoadingScreenPresented=true;Time.Update(1f/60);manager.UpdateInternal();if(manager.ActiveScene?.Name!="Scenes/Next.bytescene")throw new Exception("Loading transition did not complete");manager.UnloadScene();Console.WriteLine("PASS Deferred load event, failed-load preservation, scene path validation and quit handler");}
}
