<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmMainJSPath>wwwroot/main.js</WasmMainJSPath>
    <WasmBuildNative>false</WasmBuildNative>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <ProjectReference Include="../../Plugins/DuneCompany/DuneCompany.Plugin.csproj" />
    <ProjectReference Include="../../Plugins/DesertTerrain/DesertTerrain.Plugin.csproj" />
    <ProjectReference Include="../../Engine/ByteEngine.Core/ByteEngine.Core.csproj" />
    <WasmExtraFilesToDeploy Include="wwwroot/**/*" TargetPath="%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Include="../../Editor/ByteEngine.Editor/Resources/Fonts/**/*" Link="wwwroot/Resources/Fonts/%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
