from pathlib import Path
p=Path('Engine/ByteEngine.Core/Construction/VehicleBuilder3D.cs')
s=p.read_text()
s=s.replace('        CreateHud();','        if(FreeBuilding) StartAssembly();\n        if(FreeBuilding) CreateFreeHud(); else CreateHud();')
s=s.replace('        _markers = Layout.ActiveMounts.Select','        _markers = (FreeBuilding ? Array.Empty<VehicleMount>() : Layout.ActiveMounts).Select')
s=s.replace('if (Input.IsKeyPressed(Key.R)) ResetPosition();','if (Input.IsKeyPressed(Key.R) && (!Building || !FreeBuilding)) ResetPosition();')
s=s.replace('        if (Building)\n        {\n            bool control=', '        if (Building && FreeBuilding) UpdateFreeBuilding(clickedUi);\n        else if (Building)\n        {\n            bool control=')
s=s.replace('        FollowRoofPayload();\n        RefreshHud();','        if(!FreeBuilding) FollowRoofPayload();\n        else if(!Building) ApplyAssemblyPose(_freeSteering);\n        RefreshHud();',1)
s=s.replace('        if (VehicleBuildLayout.PartFiles[index]=="scrap_frame_long")','        if (!FreeBuilding && VehicleBuildLayout.PartFiles[index]=="scrap_frame_long")')
s=s.replace('        int available=Array.FindIndex(Layout.ActiveMounts,','        if(FreeBuilding) {RefreshFreeGhost(); return;}\n        int available=Array.FindIndex(Layout.ActiveMounts,',1)
s=s.replace('    private void PlaceSelected()\n    {','    private void PlaceSelected()\n    {\n        if(FreeBuilding){PlaceFreePreview();return;}')
s=s.replace('    private void RemoveSelected()\n    {','    private void RemoveSelected()\n    {\n        if(FreeBuilding){RemoveAssemblyPart(_selectedBlock);return;}')
s=s.replace('    private void RefreshGhost()\n    {','    private void RefreshGhost()\n    {\n        if(FreeBuilding){RefreshFreeGhost();return;}')
s=s.replace('    public bool BeginDriving()\n    {','    public bool BeginDriving()\n    {\n        if(FreeBuilding)return BeginAssemblyDriving();')
s=s.replace('            foreach(var mechanism in _mechanisms.Values) mechanism.Stop();','            foreach(var mechanism in _mechanisms.Values) mechanism.Stop();\n            if(FreeBuilding) {foreach(var rig in _assemblyRigs.Values)rig.Stop();ApplyAssemblyPose();Transform.WorldPosition=new(Transform.WorldPosition.X,Math.Max(1.25f,Assembly!.RideHeight),Transform.WorldPosition.Z);}')
s=s.replace('    public void StepDrive(float throttle, float steering, bool brake, float dt, bool drift=false)\n    {','    public void StepDrive(float throttle, float steering, bool brake, float dt, bool drift=false)\n    {\n        if(FreeBuilding){_freeSteering=steering;StepAssemblyDrive(throttle,steering,brake,dt,drift);return;}')
s=s.replace('        foreach(var pair in _mechanisms)\n        {\n            string? action=Layout.Parts[pair.Key] switch','        foreach(var pair in ActiveRigs())\n        {\n            string? action=pair.File switch')
s=s.replace('pair.Value.IsPlaying && PlayClip(pair.Value,action,false)', 'pair.Rig.IsPlaying && PlayClip(pair.Rig,action,false)')
s=s.replace('pair.Value.Seek(0); fired++','pair.Rig.Seek(0); fired++')
s=s.replace('pair.Value.CurrentAnimation.EndsWith("__AimYaw")','pair.Rig.CurrentAnimation.EndsWith("__AimYaw")')
s=s.replace('if (powered) PlayClip(pair.Value,action,true); else pair.Value.Pause();','if (powered) PlayClip(pair.Rig,action,true); else pair.Rig.Pause();')
s=s.replace('pair.Value.Seek(0); count++','pair.Rig.Seek(0); count++')
s=s.replace('|| Layout.HasTracks) return;','|| (FreeBuilding ? Assembly!.HasTracks : Layout.HasTracks)) return;')
s=s.replace('Transform.WorldPosition=new(0,Layout.RideHeight,0);','Transform.WorldPosition=new(0,FreeBuilding && Assembly!=null ? (Building?Math.Max(1.25f,Assembly.RideHeight):Assembly.RideHeight) : Layout.RideHeight,0);')
s=s.replace('    public void SaveBuild()\n    {','    public void SaveBuild()\n    {\n        if(FreeBuilding){SaveAssembly();return;}')
s=s.replace('    public void LoadBuild()\n    {','    public void LoadBuild()\n    {\n        if(FreeBuilding){LoadAssembly();return;}')
s=s.replace('    protected override void OnStop()\n    {','    protected override void OnStop()\n    {\n        foreach(var obj in _assemblyVisuals.Values.ToArray())if(obj.Scene!=null)obj.Scene.DestroyGameObject(obj);\n        _assemblyVisuals.Clear();_assemblyRigs.Clear();_assemblyUndo.Clear();_assemblyRedo.Clear();_freeCardBorders.Clear();Assembly=null;')
s=s.replace('Color=new(.91f,.94f,.82f,1), ShadowColor=new(0,0,0,.85f), OrderInLayer=10','Color=new(.91f,.90f,.86f,1), FontReference=new AssetReference("Assets/GarageUI/fonts/Barlow-Regular.ttf"), ShadowColor=new(0,0,0,.20f), ShadowOffset=new(0,1), OrderInLayer=10')
s=s.replace('FontSize=16, Offset=offset','FontSize=16, FontReference=new AssetReference("Assets/GarageUI/fonts/BarlowCondensed-SemiBold.ttf"), Offset=offset')
p.write_text(s)
p=Path('Engine/ByteEngine.Core/Construction/VehicleBuilder3D.GaragePresentation.cs');s=p.read_text()
s=s.replace('[[0,1,2,3,25,9,10],[4,5,11,12,13,14]', '[[0,1,2,3,25,9,10],[4,5,11,12,13,14,15]')
s=s.replace('    {\n        if(!Building || chassis','    {\n        if(FreeBuilding)return ReplaceAssemblyRoot(chassis);\n        if(!Building || chassis',1)
s=s.replace('    public bool UndoBuild()\n    {','    public bool UndoBuild()\n    {\n        if(FreeBuilding)return UndoAssembly(false);')
s=s.replace('    public bool RedoBuild()\n    {','    public bool RedoBuild()\n    {\n        if(FreeBuilding)return UndoAssembly(true);')
s=s.replace('        return point.Y<70','        if(FreeBuilding)return point.Y<48 || point.Y>540 || (point.X<198 && point.Y<260);\n        return point.Y<70')
s=s.replace('    private void RefreshPalette()\n    {','    private void RefreshPalette()\n    {\n        if(FreeBuilding){RefreshFreePalette();return;}')
s=s.replace('    private void RefreshHud()\n    {','    private void RefreshHud()\n    {\n        if(FreeBuilding){RefreshFreeHud();return;}')
p.write_text(s)
p=Path('Engine/ByteEngine.Core/Construction/VehicleBuilder3D.FreeConstruction.cs');s=p.read_text().replace('    private int _hoveredBlock','    private float _freeSteering;\n    private int _hoveredBlock');p.write_text(s)
p=Path('Engine/ByteEngine.Core/Construction/VehicleBuilder3DCodec.cs');s=p.read_text().replace('["driftGrip"]=builder.DriftGrip','["driftGrip"]=builder.DriftGrip, ["freeBuilding"]=builder.FreeBuilding').replace('        Assets=context.Assets','        FreeBuilding=data.Properties["freeBuilding"]?.GetValue<bool>() ?? true,\n        Assets=context.Assets');p.write_text(s)
p=Path('Tests/ByteEngine.Tests/GoblinVehicleDiagnostic.cs');s=p.read_text().replace('        Scenes.LoadScene(scene);','        builder.FreeBuilding=false;\n        Scenes.LoadScene(scene);');p.write_text(s)
