using System.Globalization;
using System.Numerics;
using ByteEngine.Core;
using ByteEngine.Core.Assets;
using ByteEngine.Core.Graphics;
using ByteEngine.Core.Scene;
namespace DuneCompany;
public sealed partial class DuneWorkshop3D
{
 readonly List<(UiWidget button,Action action)> _buttons=[];readonly Dictionary<string,GameObject> _ui=[];int _tuning=-1,_drag=-1,_typing=-1;string _input="";bool _replace;
 void RefreshHud(){Text("Machine count",$"{_blocks.Count} BLOCKS / {_blocks.Sum(b=>_catalog[b.Type].Mass):0} kg");Text("Machine status",Building?"WORKSHOP":$"{Math.Abs(Speed)*3.6f:0} km/h");Text("Simulation mode",Building?"BUILD":"DRIVE");Text("Placement instruction",_message);if(Building)Text("Battle objective","PROVING CONTRACT / Build a machine and press B");}
 void Text(string name,string value){if(_ui.TryGetValue(name,out var o)&&o.GetComponent<UiText>() is {} t)t.Text=value;}
 void Bind(string name,Action action){if(_ui.TryGetValue(name,out var o)&&o.GetComponent<UiWidget>() is {} w)_buttons.Add((w,action));}
 void BindUi()
 {
  foreach(var o in GameObject.Scene!.GameObjects.Where(o=>o.GetComponent<UiText>()!=null||o.GetComponent<UiWidget>()!=null||o.GetComponent<UiCanvas>()!=null))_ui[o.Name]=o;
  Text("Workshop title","DUNE COMPANY");Text("Placement instruction",_message);Text("Machine count",$"{_blocks.Count} BLOCKS / {_blocks.Sum(b=>_catalog[b.Type].Mass):0} kg");Text("Battle objective","PROVING CONTRACT / Build a machine and press B");Text("Build controls","MMB or RMB orbit / Scroll zoom / R yaw / F pitch / G roll / T face / B drive");
  foreach(var (name,command) in new[]{("Run / build","Toggle drive"),("Undo","Undo"),("Redo","Redo"),("Save machine","Save vehicle"),("Load machine","Load vehicle"),("Recover machine","Recover vehicle")}){string c=command;Bind(name,()=>Command(c));}
  Bind("Place blocks",()=>{_tool="Place";CloseTuning();});Bind("Move branch",()=>{_tool="Move";CloseTuning();_message="Click the branch you want to move.";});Bind("Rotate mount",()=>_twist=(_twist+1)%4);Bind("Change mount face",()=>{_manualFace=true;_face=(_face+1)%6;});
  Bind("Copy part",()=>{if(_selected>=0){_type=_blocks.First(b=>b.Id==_selected).Type;_tool="Place";RefreshGhost();RefreshPalette();}});Bind("Erase blocks",()=>{_tool="Erase";CloseTuning();});Bind("Tune blocks",()=>{_tool="Tune";_message="Click a placed block to tune it.";});
  for(int i=0;i<5;i++){int index=i;Bind($"Button {8+i*42},639",()=>{_category=index;_page=0;SelectType(_catalog.Values.First(p=>p.Group==Groups[index]).Id);});}
  for(int i=0;i<6;i++){int slot=i;Bind($"Button {239+i*106},633",()=>{var parts=Palette();if(_page*6+slot<parts.Length)SelectType(parts[_page*6+slot].Id);});}
  Bind("Button 880,634",()=>{_page=Math.Max(0,_page-1);RefreshPalette();});Bind("Button 880,674",()=>{_page=Math.Min((Palette().Length-1)/6,_page+1);RefreshPalette();});
  Bind("Button 1223,88",CloseTuning);Bind("Button 944,494",()=>{if(_tuning>=0){Record();var p=_blocks.First(b=>b.Id==_tuning);p.Power=1;p.Steering=30;p.Grip=1;p.Travel=.17f;p.Angle=35;p.Stroke=.42f;p.Paint=0;p.SpringRate=4;p.Damping=1;p.Preload=0;p.SpeedLimit=32;p.BrakeStrength=1;SyncTuning();RefreshTuning();}});
  Bind("Button 1098,494",()=>{if(_tuning>=0){Record();var p=_blocks.First(b=>b.Id==_tuning);foreach(var b in _blocks.Where(b=>b.Type==p.Type)){b.Power=p.Power;b.Steering=p.Steering;b.Grip=p.Grip;b.Travel=p.Travel;b.Angle=p.Angle;b.Stroke=p.Stroke;b.Paint=p.Paint;b.SpringRate=p.SpringRate;b.Damping=p.Damping;b.Preload=p.Preload;b.SpeedLimit=p.SpeedLimit;b.BrakeStrength=p.BrakeStrength;}SyncTuning();RefreshTuning();}});
  for(int i=0;i<6;i++){int row=i;Bind($"Button 944,{158+i*57}",()=>{if(row<Settings().Length){Record();_drag=row;_typing=-1;}});Bind("Tuning numeric value "+i,()=>{if(row<Settings().Length){_typing=row;_drag=-1;_input=Value(row).ToString("0.##",CultureInfo.InvariantCulture);_replace=true;}});}
  ApplyPresentation();CloseTuning();UpdateVisibility();RefreshHud();
 }
 void UpdateTooltip(){if(!_ui.TryGetValue("Context tooltip",out var panel))return;var hover=_buttons.FirstOrDefault(pair=>pair.button.GameObject.ActiveInHierarchy&&pair.button.IsHovered).button;if(hover==null||_tuning>=0){panel.Active=false;return;}string title=hover.GameObject.Name;string help=title switch{"Run / build"=>"Deploy a mission. Finish or quit, then return to base before building.","Undo"=>"Undo the last building edit. Ctrl+Z.","Redo"=>"Redo an undone building edit. Ctrl+Y.","Save machine"=>"Save your current vehicle in this project's Saves folder.","Load machine"=>"Reload the saved vehicle into the workshop.","Place blocks"=>"Click a surface to attach the selected block.","Move branch"=>"Pick a branch, then click its new mounting surface.","Rotate mount"=>"Rotate the preview in 90 degree steps. R.","Change mount face"=>"Choose which face of the new block attaches. T.","Copy part"=>"Select the same part as the selected placed block.","Erase blocks"=>"Click a part to delete it. Attached parts remain. Another block can become the root.","Tune blocks"=>"Click a block. Drag sliders or click values to type.","Recover machine"=>"Right the vehicle locally during a mission; return to base after finishing or quitting.",_=>""};for(int i=0;i<5;i++)if(title==$"Button {8+i*42},639"){title=Groups[i];help="Choose "+Groups[i].ToLowerInvariant()+" components.";}
  for(int i=0;i<6;i++)if(title==$"Button {239+i*106},633"){int index=_page*6+i;var parts=Palette();if(index<parts.Length){var part=parts[index];title=part.Label;help=part.Function;if(part.SupportWidth>.5f||part.SupportLength>.5f)help+=$" Required support: {part.SupportWidth:0.##} x {part.SupportLength:0.##} m.";}}
  if(help.Length==0){panel.Active=false;return;}panel.Active=true;Text("Tooltip heading",title.ToUpperInvariant());Text("Tooltip explanation",help);}
 DunePart[] Palette()=>_catalog.Values.Where(p=>p.Group==Groups[_category]).OrderBy(p=>p.Id).ToArray();
 public void SelectType(int type){_type=type;_tool="Place";_twist=_pitchSteps=_rollSteps=0;_face=0;_manualFace=false;_placementNudge=Vector2.Zero;CloseTuning();RefreshGhost();RefreshPalette();}
 void RefreshPalette()
 {
  var list=Palette();for(int i=0;i<6;i++){int index=_page*6+i;bool visible=index<list.Length;foreach(string key in new[]{"Part selection "+i,"Part "+i,"Part name "+i,$"Button {239+i*106},633"})if(_ui.TryGetValue(key,out var o))o.Active=Building&&visible;if(!visible)continue;var p=list[index];Text("Part name "+i,p.Label);if(_ui.TryGetValue("Part "+i,out var image)&&image.GetComponent<UiWidget>() is {} w)w.ImageReference=new(p.Preview);if(_ui.TryGetValue("Part selection "+i,out var border)&&border.GetComponent<UiWidget>() is {} b)b.Color=p.Id==_type?new(.68f,.81f,.35f,1):Vector4.Zero;}
  Text("Selected block",_catalog[_type].Label);Text("Block function",_catalog[_type].Function);
 }
 void UpdateVisibility()
 {
  foreach(var (name,o) in _ui){if(o.GetComponent<UiWidget>() is {} widget){var rect=UiLayout.Resolve(o,widget.Anchor,widget.Offset,widget.Size,new(1280,720));if(rect.Position.Y>=570)o.Active=Building;}else if(o.GetComponent<UiText>() is {} text&&text.Offset.Y>=570)o.Active=Building;}
  foreach(string name in new[]{"Build guidance background","Placement instruction","Build controls"})if(_ui.TryGetValue(name,out var hint))hint.Active=Building; if(_ui.TryGetValue("Placement status",out var status))status.Active=false; foreach(string name in new[]{"Place blocks","Move branch","Rotate mount","Change mount face","Copy part","Erase blocks","Tune blocks","Undo","Redo","Save machine","Load machine"})if(_ui.TryGetValue(name,out var button)&&button.GetComponent<UiWidget>() is {} widget)widget.Interactable=Building; if(_ui.TryGetValue("Context tooltip",out var tooltip))tooltip.Active=false;RefreshPalette();
 }
 void UpdateUi()
 {
  foreach(var (button,action) in _buttons)if(button.GameObject.ActiveInHierarchy&&button.WasClicked&&(_typing<0||Input.IsMouseButtonPressedForUi(MouseButton.Left))){action();break;}
  if(Input.IsKeyPressed(Key.Escape)){CloseTuning();_tool="Place";_move=-1;}
  UpdateTooltip();if(_tuning<0)return;if(!_blocks.Any(b=>b.Id==_tuning)){CloseTuning();return;}
  if(_drag>=0){var track=_ui[$"Button 944,{158+_drag*57}"].GetComponent<UiWidget>()!;var rect=UiLayout.Resolve(track.GameObject,track.Anchor,track.Offset,track.Size,Input.GameViewSize);var s=Settings()[_drag];SetValue(_drag,s.min+Math.Clamp((Input.GameViewMousePosition.X-rect.Position.X)/Math.Max(1,rect.Size.X),0,1)*(s.max-s.min));if(!Input.IsMouseButtonDownForUi(MouseButton.Left))_drag=-1;RefreshTuning();}
  if(_typing>=0){string typed="";for(int i=0;i<10;i++)if(Input.IsKeyPressed((Key)((int)Key.D0+i))||Input.IsKeyPressed((Key)((int)Key.KeyPad0+i)))typed+=i;if(Input.IsKeyPressed(Key.Period)||Input.IsKeyPressed(Key.KeyPadDecimal))typed+=".";if(Input.IsKeyPressed(Key.Minus))typed+="-";if(typed.Length>0){if(_replace)_input="";_replace=false;if(_input.Length<12)_input+=typed;}if(Input.IsKeyPressed(Key.Backspace)){_input=_replace?"":_input.Length>0?_input[..^1]:"";_replace=false;}if(Input.IsKeyPressed(Key.Enter)||Input.IsKeyPressed(Key.KeyPadEnter)){if(float.TryParse(_input,NumberStyles.Float,CultureInfo.InvariantCulture,out float v)&&float.IsFinite(v)){Record();SetValue(_typing,v);}_typing=-1;}RefreshTuning();}
 }
 (string name,float min,float max,string key)[] Settings()
 {
  if(_tuning<0)return [];var p=_blocks.First(b=>b.Id==_tuning);var settings=p.Type switch{>=13 and <=15=>[("Drive multiplier",0,2,"Power"),("Tyre grip",.2f,2,"Grip"),("Brake strength",.1f,2,"BrakeStrength")],23 or 24=>[("Engine output",0,2,"Power"),("Speed limit (m/s)",4,50,"SpeedLimit")],16 or 17 or 32=>[("Travel (m)",.02f,.5f,"Travel"),("Spring stiffness (Hz)",1,12,"SpringRate"),("Damping ratio",.15f,2,"Damping"),("Preload (m)",-.1f,.1f,"Preload")],18 or 19=>[("Movement angle",-90,90,"Angle")],21=>[("Piston stroke",0,.42f,"Stroke")],30 or 31=>[("Weapon power",.2f,2,"Power")],_=>Array.Empty<(string name,float min,float max,string key)>()};return settings.Append(("Body paint",0f,5f,"Paint")).ToArray();
 }
 float Value(int row){var p=_blocks.First(b=>b.Id==_tuning);return Settings()[row].key switch{"Paint"=>p.Paint,"Power"=>p.Power,"Steering"=>p.Steering,"Grip"=>p.Grip,"Travel"=>p.Travel,"Angle"=>p.Angle,"Stroke"=>p.Stroke,"SpringRate"=>p.SpringRate,"Damping"=>p.Damping,"Preload"=>p.Preload,"SpeedLimit"=>p.SpeedLimit,"BrakeStrength"=>p.BrakeStrength,_=>0};}
 void SetValue(int row,float v){var s=Settings()[row];v=Math.Clamp(v,s.min,s.max);var p=_blocks.First(b=>b.Id==_tuning);switch(s.key){case "Paint":p.Paint=MathF.Round(v);ApplyPaint(p);break;case "Power":p.Power=v;break;case "Steering":p.Steering=v;break;case "Grip":p.Grip=v;break;case "Travel":p.Travel=v;break;case "Angle":p.Angle=v;break;case "Stroke":p.Stroke=v;break;case "SpringRate":p.SpringRate=v;break;case "Damping":p.Damping=v;break;case "Preload":p.Preload=v;break;case "SpeedLimit":p.SpeedLimit=v;break;case "BrakeStrength":p.BrakeStrength=v;break;}if(_visuals.TryGetValue(p.Id,out var visual)&&visual.GetComponent<DuneBlock3D>() is {} authored){authored.DriveMultiplier=p.Power;authored.SteeringAngle=p.Steering;authored.TyreGrip=p.Grip;}SyncTuning();BuildJson=Snapshot();}
 void SyncTuning(){foreach(var p in _blocks)if(_visuals.TryGetValue(p.Id,out var v)&&v.GetComponent<DuneBlock3D>() is {} a){ApplyPaint(p);a.MechanicalTuningAuthored=true;a.Paint=p.Paint;a.DriveMultiplier=p.Power;a.TyreGrip=p.Grip;a.Travel=p.Travel;a.Angle=p.Angle;a.Stroke=p.Stroke;a.SpringRate=p.SpringRate;a.Damping=p.Damping;a.Preload=p.Preload;a.SpeedLimit=p.SpeedLimit;a.BrakeStrength=p.BrakeStrength;}BuildJson=Snapshot();}
 void OpenTuning(){if(!Building||_selected<0)return;_tuning=_selected;_typing=_drag=-1;if(_ui.TryGetValue("Block tuning panel",out var panel))panel.Active=true;RefreshTuning();}
 void CloseTuning(){_tuning=_typing=_drag=-1;if(_ui.TryGetValue("Block tuning panel",out var panel))panel.Active=false;}
 void RefreshTuning(){if(_tuning<0)return;var p=_blocks.First(b=>b.Id==_tuning);Text("Tuning heading",_catalog[p.Type].Label.ToUpperInvariant());var settings=Settings();for(int i=0;i<6;i++){bool active=i<settings.Length;foreach(string key in new[]{"Tuning value "+i,"Tuning numeric value "+i,"Tuning slider fill "+i,$"Button 944,{158+i*57}"})if(_ui.TryGetValue(key,out var o))o.Active=active;if(!active)continue;Text("Tuning value "+i,settings[i].key=="Paint"?"Paint / "+new[]{"Stock","Rust red","Olive","Ivory","Blue","Black"}[(int)p.Paint]:settings[i].name);if(_ui.TryGetValue("Tuning numeric value "+i,out var input)&&input.GetComponent<UiWidget>() is {} w)w.Label=_typing==i?_input+"|":Value(i).ToString("0.##",CultureInfo.InvariantCulture);if(_ui.TryGetValue("Tuning slider fill "+i,out var fill)&&fill.GetComponent<UiWidget>() is {} f){f.Value=(Value(i)-settings[i].min)/(settings[i].max-settings[i].min)*100;f.Maximum=100;}}}
}
