using System.Text.Json;
using System.Security.Cryptography;
using System.Text;
using ByteEngine.Core;
using ByteEngine.Core.Graphics;
namespace DuneCompany;
public sealed partial class DuneWorkshop3D
{
 const int BlueprintPageSize=4;
 string[] _blueprintFiles=[];int _blueprintPage;string _loadedBlueprint="",_blueprintName="";bool _namingBlueprint,_replaceBlueprintName;string _deleteBlueprint="";
 sealed record BlueprintInfo(string Name);
 string BlueprintName(string file){try{var metadata=file+".name";if(File.Exists(metadata))return JsonSerializer.Deserialize<BlueprintInfo>(File.ReadAllText(metadata))?.Name??Path.GetFileNameWithoutExtension(file);}catch(Exception e)when(e is IOException or JsonException){}return Path.GetFileNameWithoutExtension(file)=="vehicle"?"Latest saved build":Path.GetFileNameWithoutExtension(file).Replace('-',' ');}
 bool EditableBlueprint(string file)=>file.Length>0&&Path.GetFullPath(Path.GetDirectoryName(file)!).Equals(Path.GetFullPath(Path.Combine(SaveRoot,"Blueprints")),StringComparison.OrdinalIgnoreCase);
 string LoadSavedText(string file)=>Path.GetFullPath(file).StartsWith(Path.GetFullPath(SaveRoot)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)?ByteEngine.Core.Runtime.GameSaveService.FromDirectory(SaveRoot).LoadText(Path.GetRelativePath(SaveRoot,file)):File.ReadAllText(file);
 void AtomicSave(string file,string data)=>ByteEngine.Core.Runtime.GameSaveService.FromDirectory(SaveRoot).SaveText(Path.GetRelativePath(SaveRoot,file),data);
 void BindBlueprintUi(){Bind("Blueprint update",()=>Command("Save vehicle"));for(int i=0;i<BlueprintPageSize;i++){int slot=i;Bind("Blueprint delete "+i,()=>DeleteBlueprint(_blueprintPage*BlueprintPageSize+slot));Bind("Blueprint row "+i,()=>LoadBlueprint(_blueprintPage*BlueprintPageSize+slot));}Bind("Blueprint previous",()=>{_deleteBlueprint="";_blueprintPage=Math.Max(0,_blueprintPage-1);RefreshBlueprints();});Bind("Blueprint next",()=>{_deleteBlueprint="";_blueprintPage=Math.Min(Math.Max(0,(_blueprintFiles.Length-1)/BlueprintPageSize),_blueprintPage+1);RefreshBlueprints();});Bind("Blueprint new",BeginBlueprintName);Bind("Blueprint name field",()=>{_namingBlueprint=true;_replaceBlueprintName=true;});Bind("Blueprint name cancel",()=>{_namingBlueprint=false;GarageActive("Blueprint naming",false);});Bind("Blueprint name confirm",SaveNamedBlueprint);RestoreBlueprintIdentity();}
 void RestoreBlueprintIdentity(){try{string file=Path.Combine(SaveRoot,"active-blueprint.txt");if(File.Exists(file)){string name=LoadSavedText(file);if(name==Path.GetFileName(name)){string candidate=Path.Combine(SaveRoot,"Blueprints",name);if(File.Exists(candidate)){_loadedBlueprint=candidate;Text("Garage vehicle name",BlueprintName(candidate));}}}}catch(IOException){}}
 void BeginBlueprintName(){if(!Building)return;OpenGarageOverlay("Blueprints overlay");_blueprintName="Vehicle "+DateTime.Now.ToString("HHmm");_replaceBlueprintName=true;_namingBlueprint=true;_deleteBlueprint="";GarageActive("Blueprint naming",true);RefreshBlueprintName();}
 void RefreshBlueprintName(){if(_ui.TryGetValue("Blueprint name field",out var field))field.GetComponent<UiWidget>()!.Label=_blueprintName+(_namingBlueprint?" |":"");}
 void SaveNamedBlueprint(){if(!Building||!_namingBlueprint)return;string name=_blueprintName.Trim();if(name.Length==0){Text("Blueprint name hint","Enter a vehicle name before saving.");return;}string file=Path.Combine(SaveRoot,"Blueprints",Guid.NewGuid().ToString("N")+".json");AtomicSave(file,Snapshot());AtomicSave(file+".name",JsonSerializer.Serialize(new BlueprintInfo(name)));_loadedBlueprint=file;AtomicSave(Path.Combine(SaveRoot,"active-blueprint.txt"),Path.GetFileName(file));AtomicSave(Path.Combine(SaveRoot,"vehicle.json"),Snapshot());_garageSaved=true;_namingBlueprint=false;GarageActive("Blueprint naming",false);Text("Garage vehicle name",name);_blueprintPage=0;RefreshBlueprints();Text("Blueprint notice","Saved "+name+". Use Save changes to update this vehicle.");}
 void SaveCurrentBlueprint(){if(!Building)return;if(!EditableBlueprint(_loadedBlueprint)||!File.Exists(_loadedBlueprint)){BeginBlueprintName();return;}AtomicSave(_loadedBlueprint,Snapshot());AtomicSave(Path.Combine(SaveRoot,"vehicle.json"),Snapshot());_garageSaved=true;RefreshBlueprints();_message="Saved changes to "+BlueprintName(_loadedBlueprint)+".";Text("Blueprint notice",_message);}
 void DeleteBlueprint(int index){if(index<0||index>=_blueprintFiles.Length)return;string file=_blueprintFiles[index];if(!EditableBlueprint(file))return;if(_deleteBlueprint!=file){_deleteBlueprint=file;RefreshBlueprints();Text("Blueprint notice","Click CONFIRM DELETE on that card. Your current vehicle stays in the garage.");return;}File.Delete(file);if(File.Exists(file+".name"))File.Delete(file+".name");if(_loadedBlueprint==file){_loadedBlueprint="";_garageSaved=false;AtomicSave(Path.Combine(SaveRoot,"active-blueprint.txt"),"");}_deleteBlueprint="";RefreshBlueprints();Text("Blueprint notice","Blueprint deleted. Current vehicle kept.");}
 void RefreshBlueprints(){string dir=Path.Combine(SaveRoot,"Blueprints");_blueprintFiles=Directory.Exists(dir)?Directory.GetFiles(dir,"*.json").OrderByDescending(File.GetLastWriteTimeUtc).ToArray():[];string preset=Path.Combine(ProjectRoot,"Assets/RecoveryBlueprints");if(Directory.Exists(preset))_blueprintFiles=_blueprintFiles.Concat(Directory.GetFiles(preset,"*.json").OrderBy(Path.GetFileName)).ToArray();string legacy=Path.Combine(SaveRoot,"vehicle.json");if(File.Exists(legacy)&&!_blueprintFiles.Any(EditableBlueprint))_blueprintFiles=_blueprintFiles.Append(legacy).ToArray();_blueprintPage=Math.Clamp(_blueprintPage,0,Math.Max(0,(_blueprintFiles.Length-1)/BlueprintPageSize));for(int i=0;i<BlueprintPageSize;i++){int index=_blueprintPage*BlueprintPageSize+i;bool visible=index<_blueprintFiles.Length;foreach(string key in new[]{"Blueprint row ","Blueprint thumbnail ","Blueprint label ","Blueprint stats ","Blueprint delete "})GarageActive(key+i,visible);if(!visible)continue;string file=_blueprintFiles[index];string label=BlueprintName(file);Text("Blueprint label "+i,label.Length>28?label[..25]+"...":label);GarageActive("Blueprint delete "+i,EditableBlueprint(file));if(_ui.TryGetValue("Blueprint delete "+i,out var delete))delete.GetComponent<UiWidget>()!.Label=_deleteBlueprint==file?"CONFIRM DELETE":"DELETE";try{string json=LoadSavedText(file);var blocks=BuildStore.Read(json,_catalog);Text("Blueprint stats "+i,$"{blocks.Count} parts / {blocks.Sum(b=>_catalog[b.Type].Mass):0} kg"+(EditableBlueprint(file)?"":" / starter"));if(_ui.TryGetValue("Blueprint thumbnail "+i,out var image))image.GetComponent<UiWidget>()!.ImageReference=new(BlueprintThumbnail(blocks,json));}catch(Exception ex)when(ex is IOException or JsonException or InvalidDataException){Text("Blueprint stats "+i,"Could not read this blueprint");}}Text("Blueprint description","Load a vehicle / Save changes updates your loaded blueprint.");Text("Blueprint page",$"{_blueprintPage+1} / {Math.Max(1,(_blueprintFiles.Length+BlueprintPageSize-1)/BlueprintPageSize)}");}
 void LoadBlueprint(int index){if(!Building||index<0||index>=_blueprintFiles.Length)return;try{string file=_blueprintFiles[index];var blocks=BuildStore.Read(LoadSavedText(file),_catalog);Record();_blocks=blocks;BuildVisuals();_loadedBlueprint=EditableBlueprint(file)?file:"";AtomicSave(Path.Combine(SaveRoot,"active-blueprint.txt"),_loadedBlueprint.Length>0?Path.GetFileName(file):"");_garageSaved=true;_message="Blueprint loaded. Undo restores your previous vehicle.";Text("Garage vehicle name",BlueprintName(file));CloseGarageOverlay();}catch(Exception ex)when(ex is IOException or JsonException or InvalidDataException){Text("Blueprint notice","Could not load this blueprint: "+ex.Message);}}
 void UpdateBlueprintNameInput(){if(!_namingBlueprint)return;_garageTextConsumed=Input.IsKeyPressed(Key.Enter)||Input.IsKeyPressed(Key.Escape);string addition="";bool shift=Input.IsKeyDown(Key.LeftShift)||Input.IsKeyDown(Key.RightShift);for(char ch='A';ch<='Z';ch++)if(Enum.TryParse<Key>(ch.ToString(),out var key)&&Input.IsKeyPressed(key))addition+=shift?ch:char.ToLowerInvariant(ch);for(int i=0;i<10;i++)if(Input.IsKeyPressed((Key)((int)Key.D0+i)))addition+=i;if(Input.IsKeyPressed(Key.Space))addition+=" ";if(Input.IsKeyPressed(Key.Minus))addition+="-";if(addition.Length>0){if(_replaceBlueprintName)_blueprintName="";_replaceBlueprintName=false;_blueprintName=(_blueprintName+addition)[..Math.Min(32,_blueprintName.Length+addition.Length)];}if(Input.IsKeyPressed(Key.Backspace)){_blueprintName=_replaceBlueprintName?"":_blueprintName.Length>0?_blueprintName[..^1]:"";_replaceBlueprintName=false;}if(Input.IsKeyPressed(Key.Enter))SaveNamedBlueprint();if(Input.IsKeyPressed(Key.Escape)){_namingBlueprint=false;GarageActive("Blueprint naming",false);}RefreshBlueprintName();}
}
