using System.Globalization;
using ByteEngine.Core;
namespace DuneCompany;
public sealed partial class DuneWorkshop3D
{
 public int PhysicsSteps=>_physics?.LastStepCount??0;
 public double DroppedPhysicsSeconds=>_physics?.DroppedSimulationSeconds??0;
 readonly record struct FrameSample(double Time,double Delta,double Physics,double Camera,double Ui,double Feedback,double Render,double Swap,float Y,float Vy,int Steps,int Contacts,int Gen0,int Gen1,int Gen2);
 double _consoleSample;
 readonly List<FrameSample> _frameSamples=new(18000);double _diagnosticTime;bool _showDiagnostics;
 void RecordFrameDiagnostics(float dt){_consoleSample+=dt;if(_consoleSample>=.5){_consoleSample=0;if(ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.PerformanceEnabled)ByteEngine.Core.Diagnostics.SurfacePerformanceDiagnostics.RecordDetails($"DUNE mode={(Building?"build":"drive")} physics={LastDriveCpuMilliseconds:0.00}ms camera={LastCameraCpuMilliseconds:0.00}ms UI={LastUiCpuMilliseconds:0.00}ms feedback={LastFeedbackCpuMilliseconds:0.00}ms fixedSteps={_physics?.LastStepCount??0} contacts={_physics?.ContactCount??0} speed={Speed:0.0} vy={PhysicalVelocity.Y:0.000}");}_diagnosticTime+=dt;if(_frameSamples.Count<18000)_frameSamples.Add(new(_diagnosticTime,Time.DeltaTime*1000,LastDriveCpuMilliseconds,LastCameraCpuMilliseconds,LastUiCpuMilliseconds,LastFeedbackCpuMilliseconds,ByteEngineApplication.LastRenderCpuMilliseconds,ByteEngineApplication.LastSwapMilliseconds,Transform.WorldPosition.Y,PhysicalVelocity.Y,_physics?.LastStepCount??0,_physics?.ContactCount??0,GC.CollectionCount(0),GC.CollectionCount(1),GC.CollectionCount(2)));if(Input.IsKeyPressed(Key.F8))_showDiagnostics=!_showDiagnostics;if(_showDiagnostics)Text("Placement instruction",$"FRAME {Time.DeltaTime*1000:0.0} ms | PHYSICS {LastDriveCpuMilliseconds:0.0} | RENDER CPU {ByteEngineApplication.LastRenderCpuMilliseconds:0.0} | VY {PhysicalVelocity.Y:0.00} | F10 EXPORT LOG");if(Input.IsKeyPressed(Key.F10))ExportFrameDiagnostics();}
 void ExportFrameDiagnostics(){if(_frameSamples.Count==0)return;try{var folder=ProjectRoot.Contains("ByteEngineGameContent",StringComparison.OrdinalIgnoreCase)?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ByteEngine","Games","Logs","DuneCompany"):Path.Combine(SaveRoot,"Diagnostics");Directory.CreateDirectory(folder);var path=Path.Combine(folder,"frames-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".csv");using(var writer=new StreamWriter(path)){writer.WriteLine("seconds,frame_ms,physics_ms,camera_ms,ui_ms,feedback_ms,render_cpu_ms,swap_ms,height,vertical_velocity,fixed_steps,contacts,gc0,gc1,gc2");foreach(var f in _frameSamples)writer.WriteLine(FormattableString.Invariant($"{f.Time:F4},{f.Delta:F3},{f.Physics:F3},{f.Camera:F3},{f.Ui:F3},{f.Feedback:F3},{f.Render:F3},{f.Swap:F3},{f.Y:F4},{f.Vy:F4},{f.Steps},{f.Contacts},{f.Gen0},{f.Gen1},{f.Gen2}"));}File.WriteAllText(path+".txt",$"Process: {Environment.ProcessPath}\nOS: {Environment.OSVersion}\nSamples: {_frameSamples.Count}\nRender values measure CPU submission; GPU completion is not measured. Swap includes presentation waiting. F8 overlay, F10 export; automatic export when scene stops.\n");_message="Diagnostics exported: "+path;Console.WriteLine(_message);}catch(Exception e){Console.WriteLine("Diagnostics export failed: "+e.Message);}}
}
