using System.Numerics;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Buffers.Binary;
using ByteEngine.Core.Graphics.ThreeD;
using ByteEngine.Core.Graphics;
using StbImageSharp;
using ByteEngine.Core.Assets;
namespace DuneCompany;
public sealed partial class DuneWorkshop3D
{
 // A cached isometric preview of the actual imported meshes. No per-frame render target or extra scene camera.
 public void BakeStarterWebPreviews(){var directory=Path.Combine(ProjectRoot,"Assets/RecoveryBlueprints");foreach(var source in Directory.GetFiles(directory,"*.json")){var json=File.ReadAllText(source);var blocks=BuildStore.Read(json,_catalog);string reference=BlueprintThumbnail(blocks,json);var dest=Path.Combine(directory,"Previews",Path.GetFileName(reference));Directory.CreateDirectory(Path.GetDirectoryName(dest)!);File.Copy(Path.Combine(SaveRoot,"BlueprintPreviews",Path.GetFileName(reference)),dest,true);if(!File.Exists(dest+".meta")){var metadata=File.ReadAllText(Path.Combine(ProjectRoot,_catalog[1].Preview)+".meta");var node=System.Text.Json.Nodes.JsonNode.Parse(metadata)!;node["guid"]=Guid.NewGuid().ToString();File.WriteAllText(dest+".meta",node.ToJsonString());}}}
 string BlueprintThumbnail(List<PlacedBlock> blocks,string json)
 {
  string hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes("mesh-preview-v5"+json)))[..24];string reference="Saves/BlueprintPreviews/"+hash+".png",file=Path.Combine(SaveRoot,"BlueprintPreviews",hash+".png");string prepared="Assets/RecoveryBlueprints/Previews/"+hash+".png";if(OperatingSystem.IsBrowser()&&File.Exists(Path.Combine(ProjectRoot,prepared)))return prepared;if(File.Exists(file)){Assets!.RegisterRuntimeTexture(reference,File.ReadAllBytes(file));return reference;}
  var textureCache=new Dictionary<string,ImageResult?>();var triangles=new List<(Vector3 a,Vector3 b,Vector3 c,Vector4 color,Vector2 ua,Vector2 ub,Vector2 uc,ImageResult? texture)>();var scene=GameObject.Scene!;var holder=scene.CreateGameObject("Blueprint thumbnail staging");holder.Active=false;
  try{foreach(var block in blocks){var obj=Model(scene,Assets!,_catalog[block.Type].File,holder,"Preview part");obj.Transform.LocalPosition=block.P;obj.Transform.LocalRotation=block.Q;foreach(var node in Descendants(obj)){var renderer=node.GetComponent<MeshRenderer>();if(renderer?.Mesh==null)continue;var vertices=renderer.Mesh.VertexData.Span;var indices=renderer.Mesh.IndexData.Span;var matrix=node.Transform.WorldMatrix;Vector3 Vertex(uint i){int at=(int)i*8;var data=renderer.Mesh.VertexData.Span;return Vector3.Transform(new(data[at],data[at+1],data[at+2]),matrix);}ImageResult? albedo=null;string textureKey=_catalog[block.Type].File+renderer.MaterialReference?.SubAssetKey;if(!OperatingSystem.IsBrowser()&&!textureCache.TryGetValue(textureKey,out albedo)){var material=Assets!.LoadModel(new AssetReference(_catalog[block.Type].File)).Materials.FirstOrDefault(m=>m.Key==renderer.MaterialReference?.SubAssetKey);if(material?.BaseColorTexture is {} source&&source.EncodedData.Length>0)albedo=ImageResult.FromMemory(source.EncodedData,ColorComponents.RedGreenBlueAlpha);textureCache[textureKey]=albedo;}Vector2 Uv(uint i){int at=(int)i*8;var data=renderer.Mesh.VertexData.Span;return new(data[at+6],data[at+7]);}var baseColor=renderer.Material?.BaseColor??new Vector4(.6f,.48f,.3f,1);if(renderer.MaterialReference?.SubAssetKey.Contains("Dune_sand",StringComparison.OrdinalIgnoreCase)==true)baseColor*=PaintColors[(int)Math.Clamp(MathF.Round(block.Paint),0,5)];for(int i=0;i<indices.Length;i+=3){var a=Vertex(indices[i]);var b=Vertex(indices[i+1]);var c=Vertex(indices[i+2]);var normal=Vector3.Cross(b-a,c-a);float lighting=normal.LengthSquared()>.0000001f?.55f+.45f*Math.Max(0,Vector3.Dot(Vector3.Normalize(normal),Vector3.Normalize(new(-.5f,1,-.4f)))):.7f;triangles.Add((Project(a),Project(b),Project(c),new(baseColor.X*lighting,baseColor.Y*lighting,baseColor.Z*lighting,1),Uv(indices[i]),Uv(indices[i+1]),Uv(indices[i+2]),albedo));}}}}
  finally{scene.DestroyGameObject(holder);}
  int width=OperatingSystem.IsBrowser()?282:564,height=OperatingSystem.IsBrowser()?86:172;var pixels=new byte[width*height*4];var depth=Enumerable.Repeat(float.NegativeInfinity,width*height).ToArray();if(triangles.Count>0){var points=triangles.SelectMany(t=>new[]{t.a,t.b,t.c}).ToArray();float lowX=points.Min(p=>p.X),highX=points.Max(p=>p.X),lowY=points.Min(p=>p.Y),highY=points.Max(p=>p.Y);float scale=Math.Min((width-32)/Math.Max(.01f,highX-lowX),(height-24)/Math.Max(.01f,highY-lowY));Vector3 Fit(Vector3 p)=>new((p.X-(lowX+highX)*.5f)*scale+width*.5f,(p.Y-(lowY+highY)*.5f)*scale+height*.5f,p.Z);foreach(var t in triangles){var a=Fit(t.a);var b=Fit(t.b);var c=Fit(t.c);float area=Edge(a,b,c.X,c.Y);if(Math.Abs(area)<.0001f)continue;int x0=Math.Clamp((int)Math.Floor(Math.Min(a.X,Math.Min(b.X,c.X))),0,width-1),x1=Math.Clamp((int)Math.Ceiling(Math.Max(a.X,Math.Max(b.X,c.X))),0,width-1),y0=Math.Clamp((int)Math.Floor(Math.Min(a.Y,Math.Min(b.Y,c.Y))),0,height-1),y1=Math.Clamp((int)Math.Ceiling(Math.Max(a.Y,Math.Max(b.Y,c.Y))),0,height-1);for(int y=y0;y<=y1;y++)for(int x=x0;x<=x1;x++){float wa=Edge(b,c,x+.5f,y+.5f)/area,wb=Edge(c,a,x+.5f,y+.5f)/area,wc=1-wa-wb;if(wa<0||wb<0||wc<0)continue;float z=wa*a.Z+wb*b.Z+wc*c.Z;int idx=y*width+x;if(z<=depth[idx])continue;depth[idx]=z;Vector4 color=t.color;if(t.texture is {} tex){var uv=t.ua*wa+t.ub*wb+t.uc*wc;int tx=Math.Clamp((int)((uv.X-MathF.Floor(uv.X))*tex.Width),0,tex.Width-1),ty=Math.Clamp((int)((uv.Y-MathF.Floor(uv.Y))*tex.Height),0,tex.Height-1),ti=(ty*tex.Width+tx)*4;var tp=tex.Data;color*=new Vector4(tp[ti]/255f,tp[ti+1]/255f,tp[ti+2]/255f,1);}int px=idx*4;pixels[px]=(byte)(Math.Clamp(color.X*1.35f,0,1)*255);pixels[px+1]=(byte)(Math.Clamp(color.Y*1.35f,0,1)*255);pixels[px+2]=(byte)(Math.Clamp(color.Z*1.35f,0,1)*255);pixels[px+3]=255;}}}
  Directory.CreateDirectory(Path.GetDirectoryName(file)!);using var output=File.Create(file);output.Write(new byte[]{137,80,78,71,13,10,26,10});byte[] header=new byte[13];BinaryPrimitives.WriteInt32BigEndian(header.AsSpan(0,4),width);BinaryPrimitives.WriteInt32BigEndian(header.AsSpan(4,4),height);header[8]=8;header[9]=6;PreviewChunk(output,"IHDR",header);using var compressed=new MemoryStream();using(var z=new ZLibStream(compressed,CompressionLevel.Fastest,true))for(int y=height-1;y>=0;y--){z.WriteByte(0);z.Write(pixels,y*width*4,width*4);}PreviewChunk(output,"IDAT",compressed.ToArray());PreviewChunk(output,"IEND",[]);output.Dispose();Assets!.RegisterRuntimeTexture(reference,File.ReadAllBytes(file));return reference;
 }
 static Vector3 Project(Vector3 p)=>new(Vector3.Dot(p,new(.8f,0,-.6f)),Vector3.Dot(p,new(.3f,.866f,.4f)),Vector3.Dot(p,new(-.52f,.5f,-.693f)));
 static float Edge(Vector3 a,Vector3 b,float x,float y)=>(x-a.X)*(b.Y-a.Y)-(y-a.Y)*(b.X-a.X);
 static void PreviewChunk(Stream stream,string type,byte[] data){byte[] name=Encoding.ASCII.GetBytes(type),size=new byte[4];BinaryPrimitives.WriteInt32BigEndian(size,data.Length);stream.Write(size);stream.Write(name);stream.Write(data);uint crc=0xffffffff;foreach(byte b in name.Concat(data)){crc^=b;for(int i=0;i<8;i++)crc=(crc>>1)^((crc&1)==1?0xedb88320u:0);}BinaryPrimitives.WriteUInt32BigEndian(size,~crc);stream.Write(size);}
}
